### ISSUE TITLE
Redirect after signup/Registration

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#1]
After registration, the URL is not redirected to the login page. Instead of this, it is showing error.

> `NoReverseMatch at /register/
Reverse for 'Login' not found. 'Login' is not a valid view function or pattern name.`

**Comment by Akshi149** [comment]
Hii @harsh-9in I would like to work on this issue.

**Comment by harsh-9in** [comment]
Hey @Akshi149, Go adhead :)
