### ISSUE TITLE
Create a favicon for the site

### ISSUE THREAD

**Issue by shraddhavp** [harsh-9in/Blogger#105]
A favicon to the site will be good with the logo

**Comment by shraddhavp** [comment]
would like to take up this issue

**Comment by Kajol-Kumari** [comment]
Hey @shraddhavp thanks for the issue but we have already covered this issue [her](https://github.com/harsh-9in/Blogger/issues/17). Feel free to close this one.

**Comment by shraddhavp** [comment]
ya sure @Kajol-Kumari
