### ISSUE TITLE
[Feature] Add contributors.md

### ISSUE THREAD

**Issue by Kajol-Kumari** [harsh-9in/Blogger#107]
**Feature requested**

Currently we don't have a `contributors.md` file to showcase our awesome contributors.

**Deliverable**

- [ ] Create `contributors.md` file having Contributor Details (Use Details from [here](https://github.com/harsh-9in/Blogger/graphs/contributors))

**Comment by ymaheshwari1** [comment]
I am interested in this.

**Comment by Kajol-Kumari** [comment]
Hey @ymaheshwari1 you already have 3 issues on your plate so lets keep this for newbies or other contributors.

**Comment by shraddhavp** [comment]
interested @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Please go ahead @shraddhavp
