### ISSUE TITLE
Design a wireframe for Home page 

### ISSUE THREAD

**Issue by Swarnimashukla** [harsh-9in/Blogger#11]
**Task**

You are supposed to create a landing page for website where user can read and write blogs .

**Features** 

We can add following features on website but not restricted to these you can use your own creativity .
1. Header ( home , about us , notification, search , user account)
2. Body (Blogs and articles written by user , category section for different kind of articles eg: entertainment , technology, science ,)
3. Footer(social media links, contact us , newsletter section )

**Again these are suggestions we would love to see your creativity** 

**Implementation**

Tools used : Figma , Balsamiq (make sure you create professional wireframes )
Create designs and share screenshots in comment section
Once finalized create PR

**Procedure**

Claim this issue: Comment below that you want to work on this issue
Write relevant commit message while making a PR
Create a PR with self closing tags 

**Inspiration** 
You can have a look at quora and check what are some must have features in such websites

**Comment by ymaheshwari1** [comment]
I want to work on this issue.

**Comment by swapniltripathi123** [comment]
![Homepageui wireframe](https://user-images.githubusercontent.com/57709091/90221540-fdb7e680-de27-11ea-8aa8-c1194aded337.PNG)

**Comment by swapniltripathi123** [comment]
![Homepageui wireframe](https://user-images.githubusercontent.com/57709091/90221592-1cb67880-de28-11ea-8590-49af5051dfe9.PNG)
    
please review it .

**Comment by swapniltripathi123** [comment]
![Homepageui wireframe](https://user-images.githubusercontent.com/57709091/90221683-41125500-de28-11ea-9822-6f69780047fe.PNG)

please review it ma'am @Swarnimashukla

**Comment by swapniltripathi123** [comment]
![Homepageui wireframe](https://user-images.githubusercontent.com/57709091/90231327-a3735180-de38-11ea-951c-ee1bc69c1366.PNG)

**Comment by Swarnimashukla** [comment]
@swapniltripathi123  good work , can you create footer like we see on websites  and arrange elements as currently it has all elements but doesn't give a look of complete website . Wireframes are blueprints of exact website so it is important to take care of every small detail .

**Comment by ymaheshwari1** [comment]
@Swarnimashukla I am working on designing the wireframe, as it is assigned to me

**Comment by Swarnimashukla** [comment]
@ymaheshwari1  yes due to some confusion swapnil tripathi completed this issue so just for this one issue we are considering both contributions and scores will be awarded to both of you. We have shared guidelines in group as well that nobody works on any issue without getting assigned .

**Comment by swapniltripathi123** [comment]
> @swapniltripathi123 good work , can you create footer like we see on websites and arrange elements as currently it has all elements but doesn't give a look of complete website . Wireframes are blueprints of exact website so it is important to take care of every small detail 

yes sure , I will do that @Swarnimashukla ma'am.

**Comment by swapniltripathi123** [comment]
> @Swarnimashukla I am working on designing the wireframe, as it is assigned to me

@ymaheshwari1 I'm sorry buddy for this . I didn't read the instructions before,,,my bad . I found out later that there is a "assignees" procedure .

**Comment by ymaheshwari1** [comment]
> @ymaheshwari1 I'm sorry buddy for this . I didn't read the instructions before,,,my bad . I found out later that there is a "assignees" procedure .

@swapniltripathi123 No problem. I was just confirming the things.

**Comment by ymaheshwari1** [comment]
Please review the below wireframe for the Home Page and provide your feedback on the same @harsh-9in @Swarnimashukla @Kajol-Kumari 

![image](https://user-images.githubusercontent.com/41404838/90325943-a76db380-df9f-11ea-8541-87d2d1f4b38a.png)

**Comment by Swarnimashukla** [comment]
@ymaheshwari1  

✨Its awesome, good work .You have covered all major components ✨

My suggestions would be : 

1. Keep search bar in header only 
2. In  place of search bar include a slider which shows top trending blogs , blog of the day etc.
3. In blog area , include like dislike ,comment option ,  it will help reader give his reviews , reactions , suggestions  and share via social media option so that person can share blog with others 
4. Divide footer in two or three section and keep newsletter inside that because otherwise it is taking up content space 

These are few small but important things to consider :🙌

**Comment by ymaheshwari1** [comment]
@Swarnimashukla 
Thanks for your suggestions. I will work on them.
For the 4th point, the newsletter component is inside the footer only but I have changed its background-color so that it will look like a separate action and thus will drive the user's mind towards it.

**Comment by ymaheshwari1** [comment]
@Swarnimashukla Updated the wireframe for the Home page.

![image](https://user-images.githubusercontent.com/41404838/90328913-ffb3ae00-dfbd-11ea-963b-df18f1fc685f.png)

**Comment by Swarnimashukla** [comment]
@ymaheshwari1  This looks good to me , you can make a pr for this issue now .

**Comment by swapniltripathi123** [comment]
![HPUWPNG](https://user-images.githubusercontent.com/57709091/90356293-aeaec300-e06c-11ea-9c8e-1948814de074.PNG)


plzz review this .

**Comment by Swarnimashukla** [comment]
@swapniltripathi123  good work , we can go for pr with this wireframe now ✨
