### ISSUE TITLE
Updating tests.py

### ISSUE THREAD

**Issue by AkM-2018** [harsh-9in/Blogger#110]
**Is your feature request related to a problem? Please describe.**
It often happens that someone adds a new feature or makes some change in the code, and it indirectly breaks another feature. Django provides tests.py to avoid such cases.   

**Describe the solution you'd like**
Whenever one adds a new feature, before putting a pull request he/she should run the tests.py. If it returns passed, the new code doesn't break previous features. Else it returns failed and the test which it was not able to pass, so that it can be fixed before putting a pull request. tests.py should be updated for every new feature which gets added.

**Comment by AkM-2018** [comment]
I would like to work on this

**Comment by harsh-9in** [comment]
go ahead @AkM-2018 :+1:

**Comment by harsh-9in** [comment]
@AkM-2018 are you still working on this issue?

**Comment by AkM-2018** [comment]
@harsh-9in, you can reassign it to someone else. I'm not able to give it enough time. I'm really sorry.

**Comment by harsh-9in** [comment]
ok no problem :smile:
