### ISSUE TITLE
Code Landing/Home page of blogger 

### ISSUE THREAD

**Issue by Swarnimashukla** [harsh-9in/Blogger#112]
**Is your feature request related to a problem? Please describe.**
Code home page/landing page of blogger as per new UI designs, in this issue we focus on developing front-end of website .

**Describe the solution you'd like**
For design check  issue #77  
Write clean code 
Follow good coding practices 

**Additional context**
Use logo design as mentioned in ui 
Use icons as well with home, notifications etc on header
Changes can be made if required but overall layout remains same

**Comment by ymaheshwari1** [comment]
Interested.

**Comment by ymaheshwari1** [comment]
@Swarnimashukla Have a look at this.

![image](https://user-images.githubusercontent.com/41404838/92085676-c87b3480-ede6-11ea-8d8a-565a88cd1638.png)

**Comment by ymaheshwari1** [comment]
@harsh-9in @Swarnimashukla Have a look on the above UI.

**Comment by Swarnimashukla** [comment]
@ymaheshwari1   Here are few changes i would suggest :

1. Include notification in header along with icons place icons for other buttons as well
2. Remove white background from blogger logo 
3. keep everything from myblog below trending as present in ui create div or columns check for online tutorials for creating different sections on a page .
4. Keep login and register as single button

**Comment by ymaheshwari1** [comment]
@Swarnimashukla I don't have the transparent logo. Can you share it with me?

**Comment by ymaheshwari1** [comment]
@Swarnimashukla I have updated the design.

![image](https://user-images.githubusercontent.com/41404838/92877344-aefe6c00-f428-11ea-9e4a-22cbd6fb6cac.png)

**Comment by ymaheshwari1** [comment]
![image](https://user-images.githubusercontent.com/41404838/92877639-fb49ac00-f428-11ea-9efa-dbc618d88157.png)

**Comment by Swarnimashukla** [comment]
@ymaheshwari1  great , just remove thing after myblog, it is taking up space unnecessarily and in future if more real time blogs will be present it can be shown , right now i feel it is just adding up to code length and not useful 
Once you make this change go for pr 👍

**Comment by ymaheshwari1** [comment]
@Swarnimashukla Can you mark the space on the above screenshot?

**Comment by ymaheshwari1** [comment]
@Swarnimashukla Have a look at this.

![image](https://user-images.githubusercontent.com/41404838/92996190-6083c700-f527-11ea-98ae-b52bb5cfa6e2.png)

**Comment by Swarnimashukla** [comment]
alright,  go for pr @ymaheshwari1  check #141  on how to make pr. you can just include main content code as we have header and footer html codes.
