### ISSUE TITLE
Code dashboard page of blogger

### ISSUE THREAD

**Issue by Swarnimashukla** [harsh-9in/Blogger#113]
Is your feature request related to a problem? Please describe.
Code dashboard page of blogger as per new UI designs, in this issue we focus on developing front-end of website.

Describe the solution you'd like
For design check issue #78 and #77 to implement similar color code and design
For graph you can use [chart.js](https://www.chartjs.org/) and google analytics 
Write clean code
Follow good coding practices

Additional context
Use logo design as mentioned in ui
Changes can be made if required but overall layout remains same

**Comment by shraddhavp** [comment]
interested @Swarnimashukla

**Comment by Swarnimashukla** [comment]
@shraddhavp  are you working on this issue ?

**Comment by shraddhavp** [comment]
> @shraddhavp are you working on this issue ?

yes @Swarnimashukla  mam working will be ready by this weekend

**Comment by shraddhavp** [comment]
![Screen Recording 2020-09-13 at 05 38 26 00 PM](https://user-images.githubusercontent.com/42699578/93017654-0d257d80-f5e8-11ea-8791-ad87e4ba87ea.gif)
@Swarnimashukla  and @Kajol-Kumari  is this ok?

**Comment by shraddhavp** [comment]
![Screen Recording 2020-09-13 at 05 41 20 87 PM](https://user-images.githubusercontent.com/42699578/93017714-7a391300-f5e8-11ea-834c-4eebc8b7637a.gif)

@Swarnimashukla  mam and @Kajol-Kumari  is this ok or any changes needed?

**Comment by Swarnimashukla** [comment]
@shraddhavp  in "your stats" section place everything  horizontally , also there were few more sections in ui design of dashboard which are not present here, try to replicate ui design into your code refer #78

**Comment by shraddhavp** [comment]
![Screen Recording 2020-09-15 at 02 26 40 49 PM](https://user-images.githubusercontent.com/42699578/93189274-901d1400-f75f-11ea-8bc5-1cd89382c67d.gif)

@Swarnimashukla mam, @Kajol-Kumari  mam and @harsh-9in  sir please look into the design of Dashboard and let me know if any changes

**Comment by Swarnimashukla** [comment]
Alright  this looks better 👍 @shraddhavp  go for pr do keep three separate files header , main content , footer in  a folder.

**Comment by shraddhavp** [comment]
any changes that i need to do before a PR? @Swarnimashukla
