### ISSUE TITLE
Code community page of blogger 

### ISSUE THREAD

**Issue by Swarnimashukla** [harsh-9in/Blogger#114]
Is your feature request related to a problem? Please describe.
Code Community page of blogger as per new UI designs, in this issue we focus on developing front-end of website.

Describe the solution you'd like
For design check issue #79  and #77 to implement similar color code and design
Write clean code
Follow good coding practices

Additional context
Use logo design as mentioned in ui
Changes can be made if required but overall layout remains same

**Comment by AdityaAshvin** [comment]
Can i work on this @Swarnimashukla ?

**Comment by AdityaAshvin** [comment]
![ss1](https://user-images.githubusercontent.com/53205379/92256880-ee413000-eef1-11ea-9d5f-50d81c85aa18.JPG)
![ss2](https://user-images.githubusercontent.com/53205379/92256885-ef725d00-eef1-11ea-9b07-362880e5eda8.JPG)

@Swarnimashukla any changes to be made?

**Comment by Swarnimashukla** [comment]
@AdityaAshvin  here are few changes i would suggest :

1. Place notification button before search bar
2. use icons along with buttons in header
3. In footer use social media icons as present in ui design this looks little dull here .

Rest everything looks fine to me @harsh-9in  what do you suggest ?

**Comment by AdityaAshvin** [comment]
> @AdityaAshvin here are few changes i would suggest :
> 
> 1. Place notification button before search bar
> 2. use icons along with buttons in header
> 3. In footer use social media icons as present in ui design this looks little dull here .
> 
> Rest everything looks fine to me @harsh-9in what do you suggest ?

okay i will make these changes.

**Comment by AdityaAshvin** [comment]
![ss1](https://user-images.githubusercontent.com/53205379/92513894-a7737300-f22e-11ea-945c-b91df1550fb9.JPG)
![ss2](https://user-images.githubusercontent.com/53205379/92513898-a8a4a000-f22e-11ea-9d39-97283ff4e248.JPG)

@Swarnimashukla Done.

**Comment by Swarnimashukla** [comment]
This looks good , go for pr @AdityaAshvin
