### ISSUE TITLE
Code community page(extension) of blogger

### ISSUE THREAD

**Issue by Swarnimashukla** [harsh-9in/Blogger#115]
Is your feature request related to a problem? Please describe.
Code community  page(extension) of blogger as per new UI designs, in this issue we focus on developing front-end of website.

Describe the solution you'd like
For design check issue #80  and #77 to implement similar color code and design
Write clean code
Follow good coding practices

Additional context
Use logo design as mentioned in ui
Changes can be made if required but overall layout remains same

**Comment by Akshi149** [comment]
Interested

**Comment by Swarnimashukla** [comment]
@Akshi149  are you working on this issue ?

**Comment by Akshi149** [comment]
@Swarnimashukla yeah

**Comment by Akshi149** [comment]
@Swarnimashukla it's almost done 
I'll upload its view by today 🙂

**Comment by Akshi149** [comment]
![ui](https://user-images.githubusercontent.com/69034239/92731333-8e83d280-f392-11ea-9c76-0d8326d7d0f9.gif)
@Swarnimashukla @harsh-9in have a look over it
any changes to be made?

**Comment by Akshi149** [comment]
Added icons in the header
@Swarnimashukla please have a look 
![127 0 0 1_8000_communities_ - Google Chrome 11-09-2020 19_32_48](https://user-images.githubusercontent.com/69034239/92935130-feaf5880-f465-11ea-981e-44e4d6d343c2.png)

**Comment by Swarnimashukla** [comment]
This looks good 👍  go for pr @Akshi149

**Comment by Akshi149** [comment]
@Swarnimashukla @Kajol-Kumari as there is already a base.html file that contains header and other parts of the website so I just added a footer and sidebar sections in it so that no changes need to be made with other pages and just extended the base.html file for this page.
So should I go with this or separately write the header and footer HTML files as mentioned in pr #141 ?

**Comment by Swarnimashukla** [comment]
@Akshi149  Keep all three parts in a folder including header , footer and your main content we will decide which header and footer to use for all pages

**Comment by harsh-9in** [comment]
Ui looks amazing.
great work @Akshi149 :+1:
