### ISSUE TITLE
Create a Information architecture for website 

### ISSUE THREAD

**Issue by Swarnimashukla** [harsh-9in/Blogger#117]
**Is your feature request related to a problem? Please describe.**
We need information architecture to have a clarity about website and features it provide , IA is basically  a user flow chart for website 

**Describe the solution you'd like**
Make a flowchart/ IA for website 
Look for all wireframe issues and ui design issues to have clarity and idea about all features we currently have  and design flowchart 

**Additional context**
Include all features and use proper symbols to shows different sections of website

**Comment by shraddhavp** [comment]
interested @Swarnimashukla

**Comment by shraddhavp** [comment]
![gloomap_14170aac](https://user-images.githubusercontent.com/42699578/91970579-7fb77300-ed35-11ea-915c-2b8b6a5a9ada.png)
 @Swarnimashukla   mam please check this out and let me know for changes

**Comment by Swarnimashukla** [comment]
good work @shraddhavp 
So here are few changes I would suggest:

1. Include about within Home page 
2. Merge profile , log-in and register and make it one button like keep register then login then profile below single button 
3. Diagram can be vertical as well if required

**Comment by shraddhavp** [comment]
ok  will do the changes

**Comment by shraddhavp** [comment]
![gloomap_ddcbd5eb](https://user-images.githubusercontent.com/42699578/91992157-6de3c900-ed51-11ea-9cca-5269bcf204a7.png)
 OR
![gloomap_6325cbf5](https://user-images.githubusercontent.com/42699578/91992262-8e138800-ed51-11ea-99fb-3568a705bbae.png)

@Swarnimashukla  mam please check it out both the images and do let me know for changes or which of the 2 is better?

**Comment by shraddhavp** [comment]
@Swarnimashukla  mam made  the changes ,please check it and let me know
![gloomap_562fe462](https://user-images.githubusercontent.com/42699578/92086269-961e0700-ede7-11ea-9411-d2a98aa969d7.png)
 OR 
![gloomap_d1a3e4f0](https://user-images.githubusercontent.com/42699578/92086307-a33af600-ede7-11ea-867e-6298a588db60.png)

**Comment by Swarnimashukla** [comment]
@shraddhavp this looks good, go for pr with first image (horizontal one)

**Comment by shraddhavp** [comment]
created PR @Swarnimashukla
