### ISSUE TITLE
Spell Mistake

### ISSUE THREAD

**Issue by ritiksoni00** [harsh-9in/Blogger#119]
![Screenshot from 2020-09-03 11-08-34](https://user-images.githubusercontent.com/47344024/92075345-e8eec300-edd5-11ea-8700-08aa40e57020.png)

It's not "RITHIK"  It is "Ritik" Should remove "H"

**Comment by ritiksoni00** [comment]
@harsh-9in  check this

**Comment by Kajol-Kumari** [comment]
@ritiksoni00 please don't go for opening a a PR until an issue gets assigned to you.

**Comment by ritiksoni00** [comment]
Okay! next time  WIll Keep in mind!!
