### ISSUE TITLE
Add contribution guidelines in README.md

### ISSUE THREAD

**Issue by Swarnimashukla** [harsh-9in/Blogger#12]
Task
Add contribution guidelines for PR generation .

**Must include points in guideline**

1. Claiming issues
2. Adding UI screenshots for design related PR .
3. Create PR to specified branch
4. Proper commit message

(For reference purpose only)

Try to be more creative and elaborate your points properly. Check for open source projects take inspiration on how to create contribution guidelines

**Procedure**

Claim this issue: Comment below that you want to work on this issue
Write relevant commit message while making a PR
Create a PR with self closing tags

Happy Learning 👍

**Comment by Akshi149** [comment]
@Swarnimashukla I would like to work on it. Please assign this to me.
