### ISSUE TITLE
Image Error of post

### ISSUE THREAD

**Issue by nooras** [harsh-9in/Blogger#126]
**Describe the bug**
If there is no Image related to user then it shouldn't show such image error as shown in screenshot.

**To Reproduce**
1. Go to home page
2. Click on blog post
3. See image error

**Expected behavior**
Image error shouldn't show if there is no image or show the default image... otherwise show the image of users

**Screenshots**
![Group 1 (2)](https://user-images.githubusercontent.com/30138146/92308517-b30b3380-efbb-11ea-9c0f-d06441797f18.png)

I want to work on this issue @Kajol-Kumari & @harsh-9in

**Comment by harsh-9in** [comment]
Go ahead @nooras

**Comment by nooras** [comment]
> Go ahead @nooras

Hey you forgot to tag assign... :P

**Comment by nooras** [comment]
Hey the image is of user not of blog... so sorry for that...

**Comment by harsh-9in** [comment]
For that it should show the default image... Is it not showing ?@nooras

**Comment by harsh-9in** [comment]
Check once by creating a new user account.

**Comment by nooras** [comment]
> For that it should show the default image... Is it not showing ?@nooras

Yes it shows the error after updating user image from backend it shows the image.  I also updated the description
![Screenshot from 2020-09-05 21-48-02](https://user-images.githubusercontent.com/30138146/92309249-84905700-efc1-11ea-897e-6e343e53a969.png)

**Comment by nooras** [comment]
So can I do this now na ? so sorry for mistake... @harsh-9in

**Comment by harsh-9in** [comment]
Yeah sure you can work on the issue 👍
