### ISSUE TITLE
Short bio in profile section

### ISSUE THREAD

**Issue by nooras** [harsh-9in/Blogger#127]
**Is your feature request related to a problem? Please describe.**
Most of the blog site have short bio of bloggers(users). What they are currently is like Software Engineer , Developer etc 

**Describe the solution you'd like**
There could be an input field of short bio. So, that blogger can add their short bio there. viewers can see and follow that user in future.

![Group 1 (3)](https://user-images.githubusercontent.com/30138146/92308901-c4a20a80-efbe-11ea-80db-fa4c877ecc18.png)

I want to work on this @harsh-9in & @Kajol-Kumari

**Comment by harsh-9in** [comment]
Go ahead @nooras 👍
