### ISSUE TITLE
Error while click on same blog of same login user

### ISSUE THREAD

**Issue by nooras** [harsh-9in/Blogger#130]
**Describe the bug**
Error occurred while clicking on same login user of same blog  

**To Reproduce**
1. Go to login page
2. Do login (let as admin)
3. Go to home page
4. Click on same blog user of same login user (let say blog written by admin)
5. See error

**Expected behavior**
Error shouldnt come while clicking on blog user on home page

**Screenshots**
Note : Watch full video

![loginbloguser](https://user-images.githubusercontent.com/30138146/92329972-f7183a00-f088-11ea-86ec-810238b43859.gif)

Want to work on this issue @harsh-9in

**Comment by harsh-9in** [comment]
Go ahead @nooras 👍

**Comment by shraddhavp** [comment]
@nooras  and @harsh-9in  this is the same issue as in #93

**Comment by nooras** [comment]
Thank you for informing @shraddhavp :) I will close this... 
Hey @harsh-9in I am closing this issuse coz it is already done by @shraddhavp ... sorrrryy for inconvenience  :)
