### ISSUE TITLE
changes in post create UI

### ISSUE THREAD

**Issue by Akshi149** [harsh-9in/Blogger#132]
**Describe the bug**
The post create page is not the same as other pages.
 
**Expected behavior**
Changing the page template to get it to match with other pages' style

**Screenshots**
Current view of the page
![127 0 0 1_8000_post_create_ - Google Chrome 06-09-2020 23_14_23](https://user-images.githubusercontent.com/69034239/92331807-dd7def00-f096-11ea-9a5a-447f05a13ef6.png)
 Want to work on this issue @harsh-9in

**Comment by harsh-9in** [comment]
so u wanna change the UI of the create post template?

**Comment by Akshi149** [comment]
yeah changing it to look similar as other pages' UI with few changes

**Comment by harsh-9in** [comment]
go ahead @Akshi149  :)

**Comment by Akshi149** [comment]
@harsh-9in 
header and footer will be added later so didn't show it here
the pink color is when the button is hovered

![127 0 0 1_8000_post_create_ - Google Chrome 22-09-2020 21_25_01](https://user-images.githubusercontent.com/69034239/93906705-2500ae00-fd1a-11ea-845f-42810fc59c64.png)
any changes you want to suggest?

**Comment by harsh-9in** [comment]
plz remove that Filter and trending part

**Comment by Akshi149** [comment]
that is actually being rendered from base.html

**Comment by harsh-9in** [comment]
okk

**Comment by harsh-9in** [comment]
looks good make pr

**Comment by Akshi149** [comment]
in that case, should I make a separate page that contains all (header, form, footer)?

**Comment by Akshi149** [comment]
header and footer will be that of #101

**Comment by harsh-9in** [comment]
first, we will go with good wireframes

**Comment by Akshi149** [comment]
> first, we will go with good wireframes

ohk 👍

**Comment by harsh-9in** [comment]
Do one thing make this as pr and I will create another issue for removing this in that you can add footer and header.
