### ISSUE TITLE
Creating a contributing.md file

### ISSUE THREAD

**Issue by shraddhavp** [harsh-9in/Blogger#134]
Would like to add the contribution guidelines and contributing details in this file
this would make it easier for contributors to look into and contribute 

the file I am planning to create would be similar to https://github.com/smaranjitghose/auto_vaidya/blob/master/CONTRIBUTING.md  which i have created

**Comment by shraddhavp** [comment]
if the issue is accepted then please assign me the issue @harsh-9in  sir

**Comment by harsh-9in** [comment]
ok go ahead @shraddhavp:+1:
