### ISSUE TITLE
[Feature] Add Markdown Styling

### ISSUE THREAD

**Issue by ManishShah120** [harsh-9in/Blogger#136]
## Is your feature request related to a problem? Please describe.
- Currently any user cannot style their blog according to their need, its stipulated to `TextField()` only, which has no support for any kind of styling.

## Describe the solution you'd like
- By the addition of the `Markdown` feature, User's would be able to add all those styling to their blog-post/article which comes with `Markdown` language.

**Comment by ManishShah120** [comment]
Hey @Kajol-Kumari , I am interested in working on this feature. Can you  assign it to me with the required labels.

**Comment by Kajol-Kumari** [comment]
Hey @ManishShah120 thanks for opening up this issue. Please go ahead with this.
