### ISSUE TITLE
Adding Pagination

### ISSUE THREAD

**Issue by kritikaparmar-programmer** [harsh-9in/Blogger#139]
**Is your feature request related to a problem? Please describe.**
Right now all the blogs are shown on one page.. We can add Pagination to just get recent 4-6 blogs on the front page and rest on others

**Describe the solution you'd like**
I would like to add pagination to the blogging site..

**Additional context**
This will make website more beautified and user interactive..

**Comment by kritikaparmar-programmer** [comment]
Hey @Kajol-Kumari , I would like to work on this.. Please assign me this issue..

**Comment by Kajol-Kumari** [comment]
Hey @kritikaparmar-programmer Thanks for opening up this issue. Please go ahead with this issue and let's keep 2-4 blogs per page.
