### ISSUE TITLE
Deleting/updating blog/post

### ISSUE THREAD

**Issue by Ahana001** [harsh-9in/Blogger#14]
Each title of post directs to new page containing feature to update or delete blog. **Add functionality to delete/update blogs through web interface.**

**Comment by Ahana001** [comment]
hope you got it!! I can do that. can I work on it??@harsh-9in

**Comment by Ahana001** [comment]
I want to add feature of delete and update post.
I can do that. can I work on it??@harsh-9in

**Comment by harsh-9in** [comment]
Till the feature of redirecting to a new page after clicking the title is not present. @Joshitha18 is working on that.

**After her work, you can add a feature of deleting the post by using a button and for updating we will redirect it to the creating of post page which is under process and being handled by another participant.** 
So, I am assigning you @Ahana001  for adding both features deleting as well as updating.

**Comment by Ahana001** [comment]
she has finished her work but you has not merged it. so Can I start working on it?

**Comment by harsh-9in** [comment]
I will merge it after 15 august as the contribution period starts from 16 Aug.
How will you add that delete button for deleting before that page feature does not merge in master?
@Ahana001

**Comment by harsh-9in** [comment]
@Ahana001 have you made pr?

**Comment by Ahana001** [comment]
I am working on it!!

**Comment by harsh-9in** [comment]
Ok take your time.

**Comment by gupta-niharika** [comment]
could i work on this issue??

**Comment by Ahana001** [comment]
![Screenshot (77)](https://user-images.githubusercontent.com/50478681/90421457-0e41b880-e0d7-11ea-9f22-8f384dc4831c.png)
![Screenshot (78)](https://user-images.githubusercontent.com/50478681/90421464-10a41280-e0d7-11ea-9a1c-94161e6fa398.png)
