### ISSUE TITLE
User Posts on Profile

### ISSUE THREAD

**Issue by kritikaparmar-programmer** [harsh-9in/Blogger#143]
**Is your feature request related to a problem? Please describe.**
Currently we are showing posts of all the users all together, but we can add a feature of taking a look at the posts by a single user by clicking on his/her name.. This will redirect to profile page having the posts that the user have made in her/his past with his/her profile.

**Additional context**
It will add a new and user interactive feature to the website..

**Comment by kritikaparmar-programmer** [comment]
Hey @harsh-9in and @Kajol-Kumari,  I would like to work on this issue.. Please assign me..

**Comment by harsh-9in** [comment]
Go ahead @kritikaparmar-programmer :+1:
