### ISSUE TITLE
view count requires refreshing

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#144]
**Describe the bug**
we have a view count feature which counts the no of time that a blog is viewed but it requires refreshing for increasing that no.
It should be done without refreshing which means asynchronously.

**To Reproduce**
1. Go to home page
2. Click on any blog 

**Expected behavior**
It should be done without refreshing which means asynchronously.

**Comment by ManishShah120** [comment]
Interested @harsh-9in

**Comment by harsh-9in** [comment]
Go ahead @ManishShah120 :+1:

**Comment by ManishShah120** [comment]
Hey @harsh-9in, Can you provide me some links in reference to this issue, I am having a hard time to find some resources which I can follow to solve this issue.
--Thank You

**Comment by harsh-9in** [comment]
Hey, @ManishShah120  for this you require knowledge of ajax. After using ajax you can asynchronously make calls to the server and it will not require to refresh the page. I have attached some source to get an idea of ajax.
https://www.youtube.com/watch?v=KgnPSmrQrXI

https://simpleisbetterthancomplex.com/tutorial/2016/08/29/how-to-work-with-ajax-request-with-django.html

https://www.tutorialspoint.com/django/django_ajax.htm

**Comment by harsh-9in** [comment]
if you have any doubt feel free to ping.

**Comment by ManishShah120** [comment]
@harsh-9in, Can we move this feature to the blog-detail page, because if we move this feature to the detail page of any blog, then the updated value will be shown by default without any refresh. I am finding it tough to implement the concepts of ajax, as I have never worked with it in past.
