### ISSUE TITLE
 Want to Create a Contributor's Guidelines. 

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [harsh-9in/Blogger#147]
**Is your feature request related to a problem? Please describe.**

A Guidelines for the new geeks who are new to Open source. 
There are certain steps and instructions which should be followed by every new commerce.

**Comment by Rishikeshrajrxl** [comment]
If you think this should be applied, then plz assign me this task.

**Comment by harsh-9in** [comment]
@Rishikeshrajrxl  it is already present there in [contributing.md](https://github.com/harsh-9in/Blogger/blob/master/CONTRIBUTING.md)

**Comment by khushi0704** [comment]
Hey , is it still open  , can I work on this ?

**Comment by Rishikeshrajrxl** [comment]
Sorry it is over for now

**Comment by Kerveyfelix** [comment]
Hi. Can I work on this?
What I plan:
1) Create a file with images and pictures showcasing how to contribute to this project.
2) Include beginner's guide to contributing.

**Comment by Kerveyfelix** [comment]
I also suggest giving text about contributing for NJACK'20 along with the points.

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @harsh-9in

**Comment by Abjcodes** [comment]
Hey @harsh-9in, is this issue still open?

**Comment by atharva-upadhye-01** [comment]
@harsh-9in, I would like to know why this issue is still open when [CONTRIBUTING.md](https://github.com/harsh-9in/Blogger/blob/master/CONTRIBUTING.md) file does exists.

**Comment by harsh-9in** [comment]
@atharva-upadhye-01 Yeah  pr is merged I am closing this issue.
