### ISSUE TITLE
Tag for blog

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#152]
**Is your feature request related to a problem? Please describe.**
We should have a tag filed in our blog in which we can add one or more tags related to the blog. I am requesting for this feature because in the future we will add feature of filtering blogs by tags.

**Comment by ManishShah120** [comment]
@harsh-9in ,I am interested in working on this issue. Can you assign it to me?

**Comment by kritikaparmar-programmer** [comment]
Hey @harsh-9in I want to work on this..

**Comment by harsh-9in** [comment]
@ManishShah120  I am assigning this issue to you.

@kritikaparmar-programmer you can refer issue #154.

**Comment by harsh-9in** [comment]
You both can discuss the approach for solving issues because they are interconnected to each other.

**Comment by harsh-9in** [comment]
@kritikaparmar-programmer ping me on #154 I will assign that to you.
