### ISSUE TITLE
Icons not showing up

### ISSUE THREAD

**Issue by kritikaparmar-programmer** [harsh-9in/Blogger#153]
**Describe the bug**
The like dislike and share icons are not showing up on home page.

**To Reproduce**
 Go to home page 

**Screenshots**
![error](https://user-images.githubusercontent.com/59971890/93223158-61b62d80-f78d-11ea-9c6b-4fcf6066fe6d.png)

**Comment by kritikaparmar-programmer** [comment]
Hey @harsh-9in take a look at this issue..

**Comment by harsh-9in** [comment]
@kritikaparmar-programmer  assigned to you.
