### ISSUE TITLE
Tag Dictionary

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#154]
**Is your feature request related to a problem? Please describe.**
Check issue #152. When a  user uses a tag then It should add to the tag dictionary for further process and if that already present then it should not add but there should be a count on the tag how much time it used and that should increase.

**Comment by harsh-9in** [comment]
assigned to @kritikaparmar-programmer

**Comment by kritikaparmar-programmer** [comment]
Ok @harsh-9in ..👍

**Comment by SubhradeepSS** [comment]
@harsh-9in I am interested to work on this issue for NWOC'20. Can u assign me this issue?

**Comment by harsh-9in** [comment]
go ahead :+1:

**Comment by SubhradeepSS** [comment]
@harsh-9in I was thinking of adding a model which will store all the tags used for a blog in the database. Should I proceed with this idea?

**Comment by SubhradeepSS** [comment]
@harsh-9in Can you please review my PR #214 for this issue?

**Comment by SubhradeepSS** [comment]
@harsh-9in Can u please review my pr - #214 for NWOC
