### ISSUE TITLE
Comment feature

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#160]
**Is your feature request related to a problem? Please describe.**
There should be a comment feature where more than one authenticated user can comment.

**Comment by ManishShah120** [comment]
I can, and want to work on this issue, but I have two issues already assigned to me, Can I be assigned to work on this feature too... After solving those two issues I can start working on this.

**Comment by harsh-9in** [comment]
You have to first complete those issues first. If someone doesn't ask me to assign then I assign it to you.

**Comment by rutujadhanawade** [comment]
I would like to work on this

**Comment by harsh-9in** [comment]
Go ahead @rutujadhanawade

**Comment by nikita-1801** [comment]
I'd like to work on this issue

**Comment by harsh-9in** [comment]
@nikita-1801 this issue is already assigned you can check out another issue or create another

**Comment by rutujadhanawade** [comment]
@harsh-9in  
I think, 
First I have to create a comment field in model "post" , Then in views I need to write a code to check if the user authenticated or not then only he can comment.
Is it right ? correct me if I am wrong.
