### ISSUE TITLE
Posts with markdown styling not taking effect in the profile-view page

### ISSUE THREAD

**Issue by ManishShah120** [harsh-9in/Blogger#164]
### Describe the bug:
- The blog-posts published with markdown styling options are not taking the effects on the user profile page.

### To Reproduce:
**1**. Go to 'home page'
**2**. Click on 'user-name' present on any of your posted blogs.
**3**. See error

### Expected behavior:
Any posts published and wrote with the tools of styling options of CKEditor should take effect on the post.

### GIF
![Issueinprofileviewpage](https://user-images.githubusercontent.com/45564404/93714747-56467600-fb82-11ea-8a2e-92754e3b0836.gif)

**Comment by ManishShah120** [comment]
@Kajol-Kumari, I am interested in solving this issue, can you assign this to me with the required labels.

**Comment by harsh-9in** [comment]
@ManishShah120  you can work on this issue.👍
