### ISSUE TITLE
Login as new user and try to change the image

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#167]
**Describe the bug**
after signup/login as a new user I am not able to change my image that feature is not working.

**To Reproduce**
1. Go to http://127.0.0.1:8000/profile/
2. Click on Profile Image
3. See error

**Expected behavior**
It should change the profile

**Screenshots**

![Screenshot from 2020-09-22 18-15-37](https://user-images.githubusercontent.com/54139847/93883792-aac33000-fcff-11ea-9a46-904c6032472b.png)

**Comment by kritikaparmar-programmer** [comment]
I would like to take up this issue @harsh-9in .. Please assign me.

**Comment by harsh-9in** [comment]
go ahead @kritikaparmar-programmer
