### ISSUE TITLE
after creating blog when clicked on the creater of blog

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#168]
**Describe the bug**
After creating blog when I tap on the username it shows an error.

**To Reproduce**
1. Go to home page 
2. Click on selfusername after creating blog
See error

**Expected behavior**
It should show the profile.

**Screenshots**

![Screenshot from 2020-09-22 19-40-21](https://user-images.githubusercontent.com/54139847/93893630-78b7cb00-fd0b-11ea-8975-dd8e2b4f79f0.png)

**Comment by ManishShah120** [comment]
@harsh-9in, I want to work on this issue.

**Comment by harsh-9in** [comment]
go ahead @ManishShah120
