### ISSUE TITLE
Design a logo for Blogger 

### ISSUE THREAD

**Issue by Swarnimashukla** [harsh-9in/Blogger#17]
Task

You are supposed to design a logo for blogger . Look for designs which are already present for currently running blogging websites .

**Implementation**

Tools used : Adobe photoshop , Adobe illustrator or any other tool convenient to you.
Create designs and share screenshots in comment section
Once finalized create PR

**Procedure**

Claim this issue: Comment below that you want to work on this issue
Write relevant commit message while making a PR
Create a PR with self closing tags

**Comment by raksha009** [comment]
Hi, I would like to work on this issue. Plz assign this to me.

**Comment by ritiksoni00** [comment]
@raksha009  can we Do it together!  If it is possible???

**Comment by itsarjun12** [comment]
i also want to work on this.

**Comment by ritiksoni00** [comment]
What about this 
![image (26)](https://user-images.githubusercontent.com/47344024/90314346-b49f8980-df30-11ea-81bd-8e7e0a5a706f.png)
![image (25)](https://user-images.githubusercontent.com/47344024/90314348-b8331080-df30-11ea-8139-2f15e8538b40.png)

**Comment by itsarjun12** [comment]
![Screenshot (38)](https://user-images.githubusercontent.com/46817093/90314753-c898ba80-df33-11ea-93fd-6c3a886ed133.png)
What about this ?

**Comment by itsarjun12** [comment]
![Bloglogo](https://user-images.githubusercontent.com/46817093/90314952-2974c280-df35-11ea-9f9b-884814101ca4.png)
Png format.

**Comment by itsarjun12** [comment]
I hope this will like it.

**Comment by itsarjun12** [comment]
@Swarnimashukla ma'am please let me know how is it ?

**Comment by Swarnimashukla** [comment]
@ritiksoni00  good work you can make pr with second design , Create a separate branch name it resources and make pr in that .

@itsarjun12 I liked your concept my suggestion would be to use complete B letter and can add a pencil with white color and shades like you already provided in design pencil or pen might look more relatable to blogging .

**Comment by ritiksoni00** [comment]
Here Is Another One :-
![Annotation 2020-08-15 214729](https://user-images.githubusercontent.com/47344024/90316822-790dbb00-df42-11ea-836a-28d3c7a94821.png)
i think it is better!!??

**Comment by itsarjun12** [comment]
![logo3](https://user-images.githubusercontent.com/46817093/90317916-4071df80-df4a-11ea-92b1-27e8cb54834e.png)
I tried to add a pencil but I didn't get proper color what kind of I want to specially black and it will be very tough to add a logo because it will be draw and I don't know drawing in photoshop because I can mold designs like paper cut so I tried to give a look like pen or pencil through my paper cut design.

**Comment by neha07kumari** [comment]
I would like to work upon this issue

**Comment by neha07kumari** [comment]
Please assign me

**Comment by itsarjun12** [comment]
It's pointed shade is indicating a pen point so we can consider as pen and I also added a full "B" what you had said ma'am.

**Comment by itsarjun12** [comment]
![logo5](https://user-images.githubusercontent.com/46817093/90319563-f17e7700-df56-11ea-90a0-ded52d21a4c8.png)
Try this.

**Comment by ritiksoni00** [comment]
Please @Swarnimashukla,  @itsarjun12 is showing their work please Merge His Pr First!

**Comment by Swarnimashukla** [comment]
@itsarjun12  I find previous one better , @ritiksoni00, @itsarjun12   we also need to look for size of logo and how it looks on a website , as you can see github logo it takes a small portion of website so need to take care of that as well with very broad logo designs when minimized it doesn't look good . Check for logo design on dribbble and [behance](https://www.behance.net/search?search=logo%20designs) . 

Also it isn't necessary to use complete name of website we can see examples like swiggy (just uses a symbol to convey brand)

**Comment by itsarjun12** [comment]
![Screenshot (41)](https://user-images.githubusercontent.com/46817093/90320287-88e6c880-df5d-11ea-8440-33963f895e02.png)
![Screenshot (39)](https://user-images.githubusercontent.com/46817093/90320289-8ab08c00-df5d-11ea-9731-b022c0b520aa.png)
![Screenshot (40)](https://user-images.githubusercontent.com/46817093/90320290-8b492280-df5d-11ea-8df7-401e303ce53b.png)
All my experiments with this logo.

**Comment by itsarjun12** [comment]
![Screenshot (42)](https://user-images.githubusercontent.com/46817093/90320409-d283e300-df5e-11ea-896c-ea7a23c43b5b.png)
One more left.

**Comment by itsarjun12** [comment]
![logo6](https://user-images.githubusercontent.com/46817093/90320694-fcd6a000-df60-11ea-8927-2f0e34a538b4.png)
After applying all grey shades and strokes. It looks like this.

**Comment by itsarjun12** [comment]
![Screenshot (43)](https://user-images.githubusercontent.com/46817093/90320884-66a37980-df62-11ea-9c45-d581264ee2b9.png)

**Comment by itsarjun12** [comment]
Plan grey shade.

**Comment by itsarjun12** [comment]
Check every logo in desktop screen then you will see proper clarify and difference.

**Comment by itsarjun12** [comment]
I will try tommorow with new start if I get something creative then I will share it with you because I haven't before use Photoshop and this is my first time so I don't know much idea but atleast we can try some browsing and youtube video can help.

**Comment by Swarnimashukla** [comment]
> I will try tommorow with new start if I get something creative then I will share it with you because I haven't before use Photoshop and this is my first time so I don't know much idea but atleast we can try some browsing and youtube video can help.

@itsarjun12  sure take some time look for inspirations and then come up with design .

Happy learning 🙌

**Comment by raksha009** [comment]
![blogger](https://user-images.githubusercontent.com/57195964/90331046-70af9180-dfcf-11ea-94e0-9c29d6a85acf.png)

![blogger1](https://user-images.githubusercontent.com/57195964/90331052-760cdc00-dfcf-11ea-8c95-34338e35b2b2.png)

**Comment by raksha009** [comment]
![Light Salmon Simple Industrial Logo](https://user-images.githubusercontent.com/57195964/90331102-c5530c80-dfcf-11ea-97d4-f8fdc315508e.gif)
![Blogger Logo](https://user-images.githubusercontent.com/57195964/90331105-c71cd000-dfcf-11ea-898f-8ffbc334789e.png)

**Comment by raksha009** [comment]
![Light Salmon Simple Industrial Logo](https://user-images.githubusercontent.com/57195964/90331112-d00da180-dfcf-11ea-9658-a7ac9f61c013.gif)

**Comment by raksha009** [comment]
I have created these. Please have a look @Swarnimashukla

**Comment by raksha009** [comment]
![blogger11](https://user-images.githubusercontent.com/57195964/90331321-fda71a80-dfd0-11ea-8344-77a7b1b36738.png)

**Comment by raksha009** [comment]
![blogger11](https://user-images.githubusercontent.com/57195964/90331324-04ce2880-dfd1-11ea-8474-9821766748db.png)

**Comment by itsarjun12** [comment]
@raksha009 great, you have made very creative designs, I inspired you from.  all the best.

**Comment by itsarjun12** [comment]
![newone](https://user-images.githubusercontent.com/46817093/90332229-d3595b00-dfd8-11ea-9bc4-8d4b996bc137.png)

**Comment by Swarnimashukla** [comment]
@raksha009  well done ✨🙌 I love all of your designs, just with the first design having a book can you change color of text as with book it looks little dull can we have a little bright color in that particular design  . rest all designs are perfect 🌟

**Comment by Swarnimashukla** [comment]
@itsarjun12  awesome , make a folder with this last design and very first design you shared , folder name  -  logo_yourname make a pr with same  🌟

**Comment by raksha009** [comment]
Yeah @Swarnimashukla , I tried changing the font and color of first one ... but it wasn't giving that cool aesthetics.. so lets ignore that one.😅

**Comment by Swarnimashukla** [comment]
@raksha009  all right then we are good to go, make a folder with all designs,   keep everything in a folder name - logo_yourname make a pr with same 🌟

**Comment by itsarjun12** [comment]
@Swarnimashukla ma'am, I have done it. sorry, for the late response ma'am, I am not much aware of git commands so understanding of git takes my time but don't worry, I will be good in this soon but thank you for your patience.

**Comment by Swarnimashukla** [comment]
No Issues @itsarjun12  , and great work guys keep going .. lets see  what @neha07kumari  comes up with, Bar has been raise quite high now 🙌

**Comment by neha07kumari** [comment]
@Swarnimashukla  maam how is this looking . This was my first time i tried a bit ,changes are welcomed from anyone .
![Screenshot (57)](https://user-images.githubusercontent.com/47255445/90340915-d78e7400-dfea-11ea-9261-2f116ada2cb9.png)

**Comment by Swarnimashukla** [comment]
@neha07kumari  Hey it looks good , but maybe because of gradient you used your text styling is merging with background , try using contrast colors or use a different gradient style

**Comment by raksha009** [comment]
When will our PRs get reviewed !? @Swarnimashukla

**Comment by neha07kumari** [comment]
![Screenshot (59)](https://user-images.githubusercontent.com/47255445/90373031-da2bb080-e060-11ea-8c3f-e3fb7b193303.png)

**Comment by neha07kumari** [comment]
@Swarnimashukla  Please have a look to the above logo.

**Comment by Swarnimashukla** [comment]
@neha07kumari  this looks nice 🙌

**Comment by neha07kumari** [comment]
@Swarnimashukla  maam now can i go for the pull request?

**Comment by Swarnimashukla** [comment]
sure @neha07kumari

**Comment by shraddhavp** [comment]
want to work on issue

**Comment by shraddhavp** [comment]
![Blogger logo](https://user-images.githubusercontent.com/42699578/90497795-1f390b00-e165-11ea-8909-64c4a390638b.png)
this the logo

**Comment by shraddhavp** [comment]
please do let me know how it is @Swarnimashukla  mam

**Comment by Swarnimashukla** [comment]
@shraddhavp its nice 👍 can you write blogger in circular form around image and keep "write your way" little closer with smaller font

**Comment by shraddhavp** [comment]
yes mam @Swarnimashukla  tried to do but I think not like the way you told but something bit different
![Blogger logo1](https://user-images.githubusercontent.com/42699578/90515124-cdea4500-e17f-11ea-8cd8-55f7b3766dbb.png)

**Comment by Swarnimashukla** [comment]
@shraddhavp  this looks cool 👍 good work , please make a pr for the same

**Comment by shraddhavp** [comment]
yes mam @Swarnimashukla  created PR

**Comment by neha07kumari** [comment]
@Swarnimashukla maam created PR.
