### ISSUE TITLE
remove side bar and trending section

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#170]
**Is your feature request related to a problem? Please describe.**
currently, the template for creating a post is rendering on base.html we want it to be separate.
Because trending and side bar is present in base.html use #101 header and footer

![](https://user-images.githubusercontent.com/69034239/92331807-dd7def00-f096-11ea-9a5a-447f05a13ef6.png)

**Comment by ManishShah120** [comment]
I want to work on this issue.. @harsh-9in

**Comment by Akshi149** [comment]
I want to work on it

**Comment by harsh-9in** [comment]
@ManishShah120 Actually @Akshi149  discussed me already about this issue. Infact, It was her proposal.
So, @Akshi149 would work on this issure.
@ManishShah120 I am creating few issues soon.

**Comment by Akshi149** [comment]
![127 0 0 1_8000_post_create_ - Google Chrome 24-09-2020 00_00_12](https://user-images.githubusercontent.com/69034239/94054357-32409a00-fdf9-11ea-939f-60f81965340a.png)
@harsh-9in have a look

**Comment by harsh-9in** [comment]
looks cool :+1:

**Comment by Akshi149** [comment]
Should I change the header and footer in base.html?
Currently this is separate post page

**Comment by harsh-9in** [comment]
No no need to change there.
Is it working fine I mean all the features are working properly?

**Comment by Akshi149** [comment]
Yeah
