### ISSUE TITLE
Add a default error page template[404 Error Handler]

### ISSUE THREAD

**Issue by ManishShah120** [harsh-9in/Blogger#177]
**Is your feature request related to a problem? Please describe.**
- When any user tries to get any post that is broken or does not exist then a simplistic error page displays.
- This is due to because currently, this web app doesn't have any default template for handling the `404 Error`.

**Describe the solution you'd like**
- Add a feature in this app to handle this error and display a default page for this specific error.

**Comment by ManishShah120** [comment]
@harsh-9in I am interested in working on this issue.

**Comment by harsh-9in** [comment]
@ManishShah120 go ahead :+1:
