### ISSUE TITLE
Design a wireframe for community page 

### ISSUE THREAD

**Issue by Swarnimashukla** [harsh-9in/Blogger#18]
**Task**

You are supposed to create a community page for website where user can connect with communities related to their interest (eg: technology, science , sports , ux/ui design , programmers community etc.) .

**Features**

We can add following features on website but not restricted to these you can use your own creativity .

1. Different communities options which user can join 
2. Details section where user could get to know what community is above 
3. Options to post their blogs and read other blogs already present along with reactions and comments enabled  

Again these are suggestions we would love to see your creativity

**Implementation**

Tools used : Figma , Balsamiq (make sure you create professional wireframes )
Create designs and share screenshots in comment section
Once finalized create PR

**Procedure**

Claim this issue: Comment below that you want to work on this issue
Write relevant commit message while making a PR
Create a PR with self closing tags

**Inspiration**

You can have a look at spaces on quora , it performs similar tasks , check for flaws that page already has and try to add your creativity

**Comment by swapniltripathi123** [comment]
I want to work on this issue .

**Comment by harsh-9in** [comment]
Yeah sure @swapniltripathi123  :)

**Comment by pvalesha** [comment]
I WANT TO WORK ON THIS ISSUE

**Comment by ymaheshwari1** [comment]
Please have a look on the below wireframe for the Community Page @swapniltripathi123 @harsh-9in @Kajol-Kumari 

![image](https://user-images.githubusercontent.com/41404838/90328939-35f12d80-dfbe-11ea-9f85-1ca7b8438af1.png)


On hovering the card, the logo will be removed and the detail about the community will be displayed, like the 6th card

**Comment by Swarnimashukla** [comment]
@ymaheshwari1  include numbers as well for follow it creates a good impact and a deciding factor for anyone who wants to join 

<img width="121" alt="follow" src="https://user-images.githubusercontent.com/30214391/90329355-c3824c80-dfc1-11ea-8cfd-60e894ff06e5.PNG">

**Comment by ymaheshwari1** [comment]
![image](https://user-images.githubusercontent.com/41404838/90331622-a35b8900-dfd3-11ea-86aa-67e9a898b90f.png)

Updated wireframe for the community page @Swarnimashukla @harsh-9in

**Comment by Swarnimashukla** [comment]
@ymaheshwari1  awesome, we are good to make pr with this wireframe 👍

**Comment by swapniltripathi123** [comment]
![community](https://user-images.githubusercontent.com/57709091/90359800-81b3dd80-e077-11ea-9fbb-318761dbbe59.PNG)
 
Plzz review this.

**Comment by swapniltripathi123** [comment]
![Comm](https://user-images.githubusercontent.com/57709091/90360164-8927b680-e078-11ea-8525-04ee49038530.PNG)

plzz review it.

**Comment by Swarnimashukla** [comment]
@swapniltripathi123  This looks good but we needed a page where all communities can be shown which user can follow so community names being main part of page .Maybe we can show community in upper half of body like horizontal slides and below that you can have these posts as you have right now .

**Comment by swapniltripathi123** [comment]
@Swarnimashukla So basically I have to bring technology ,food ,etc .  in horizontal slides which is on the  left side and also have to remove "add questions" and "add answers "options also.... Right??

**Comment by Swarnimashukla** [comment]
@swapniltripathi123  yes you got it now 👍

**Comment by swapniltripathi123** [comment]
![COMMUN](https://user-images.githubusercontent.com/57709091/90631665-c2128780-e240-11ea-937f-0a58450f0ac0.PNG)


@Swarnimashukla What about this wireframe  ma'am??

**Comment by Swarnimashukla** [comment]
yes this will work @swapniltripathi123  go for a pr

**Comment by Swarnimashukla** [comment]
@pvalesha  are you working on this issue?
