### ISSUE TITLE
Create a project admin and mentor section in readme file 

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#183]
**Is your feature request related to a problem? Please describe.**
A section in the readme for project admin and mentors to recognize their hard work to grow this project.
there will be a photo (can get from GitHub) and ink their GitHub profile.

**Comment by harsh-9in** [comment]
mentors are @Kajol-Kumari @Swarnimashukla @SKAUL05

**Comment by shraddhavp** [comment]
@harsh-9in  would like to take up the issue

**Comment by harsh-9in** [comment]
go ahead @shraddhavp :+1:
