### ISSUE TITLE
[BUG] Profile Page Error

### ISSUE THREAD

**Issue by ManishShah120** [harsh-9in/Blogger#185]
**Describe the bug**
- The blogs wrote with the special tools of `CKEditor` are not being rendered as expected in the `profile` page.
- When the title of any posts is clicked to view the detailed blog an error pops out.

**To Reproduce**
1. Go to '127.0.0.1/profile'
2. Click on 'profile'
3. Click on the `dashboard` option from the dropdown menu.
4. See the error
5. See the next error by clicking on any blogs on the page.

**Expected behavior**
- The page should render all the posts written with the tools of `CKEditor` as expected.
- The detail page of that blog should open without any error.

**Screenshots/GIF**

![profilepageerror](https://user-images.githubusercontent.com/45564404/94718943-18123900-0370-11eb-9f4d-f88d547c76a7.gif)

**Comment by ManishShah120** [comment]
@harsh-9in, @Kajol-Kumari I am interested in solving this error. Can you please assign me with the required labels?

**Comment by harsh-9in** [comment]
Go ahead @ManishShah120 :+1:
