### ISSUE TITLE
replace home ui to new ui

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#187]
**Is your feature request related to a problem? Please describe.**
replace our home UI to #161

**Comment by kritikaparmar-programmer** [comment]
Hasn't she made the changes directly!
So we have to just replace the code? @harsh-9in

**Comment by harsh-9in** [comment]
we have template we have to integrate into this. So we have to replace the code and make sure all the links and features are working properly.
Do you want to work on this issue?

**Comment by Akshi149** [comment]
I would like to work on this issue @harsh-9in

**Comment by harsh-9in** [comment]
Go ahead @Akshi149 👍

**Comment by Akshi149** [comment]
@harsh-9in the UI is of community_extended page not home page

**Comment by harsh-9in** [comment]
Okk. Let me first get the home page 😀

**Comment by Akshi149** [comment]
actually the home page is already modified but he forgot to change Header, footer and color

**Comment by Akshi149** [comment]
@harsh-9in should I change the Header, Footer, and change the UI as of #161 (excluding the portion that contains Technology and the sidebar)?

**Comment by Kerveyfelix** [comment]
Can I work on this issue?

**Comment by harsh-9in** [comment]
> Can I work on this issue?

checkout issue #209
