### ISSUE TITLE
[BUG] Not able to view any blog-posts

### ISSUE THREAD

**Issue by ManishShah120** [harsh-9in/Blogger#188]
**Describe the bug**
- The detail page of any blog-post is producing this error.
- The `dashboard` option from the dropdown menu of the profile is producing this error.
- The `My favorites` option from the dropdown menu of the profile is producing this error.

**To Reproduce**
1. Go to '127.0.0.1'
2. Click on 'Click on any blog title '
3. See an error

**Expected behavior**
- On clicking on the title of any blog the detail page should open

**Screenshots/GIF**
![erroraftercommentfeatureadded](https://user-images.githubusercontent.com/45564404/94804305-39266880-0408-11eb-9a5c-c02f4e97b74c.gif)

**Additional context**
- I am not sure if this error is only poping in the case of my system or there is an actual bug.

**Comment by ManishShah120** [comment]
@harsh-9in, @Kajol-Kumari, @Swarnimashukla, @SKAUL05, Please have a look.

**Comment by rutujadhanawade** [comment]
I would like to fix this bug as a part of CH20

**Comment by kritikaparmar-programmer** [comment]
Hey @ManishShah120 I talked to @harsh-9in its main reason is the deletion of migrations folder. Lets see what solution they comes with..

**Comment by ManishShah120** [comment]
This has been solved, so closing this issue.
