### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#2]
Profile Picture is not showing after registration.

**Comment by ritiksoni00** [comment]
harsh i did not understand what it is actually about i just started learning Django

**Comment by nooras** [comment]
I saw this issue. the thing is there is 2 users data db 1 one which is created by own django admin panel. 2. You have created profile model. after registering data is going to by default admin panel not in profile. so first we have to enter data in profile model and after that we have to show it on screen. and in front end after registering user have to upload image in profile section which will shown on profile section of user later and if user is not have uploaded any profile image so we have to show bydefault blank profile image. hope you got it or assign this one it to me I can do that. @harsh-9in

**Comment by harsh-9in** [comment]
yes @nooras  you can work on this issue.
