### ISSUE TITLE
Create a PR template that suits this project.

### ISSUE THREAD

**Issue by KerinPithawala** [harsh-9in/Blogger#201]
**Describe the solution you'd like**
To ease the work of maintainer, add some checkbox in the PR request template so that a person creates pr after complying with organisations rules.

**Additional context**
It could look something like this:
-  [ ] Have you followed the [Contribution guide](https://github.com/harsh-9in/Blogger/blob/master/CONTRIBUTING.md)?
- [ ] Have you made corresponding changes to the documentation?
- [ ] Your submission doesn't break any existing feature.

**Comment by harsh-9in** [comment]
I think the pr template is already present,

**Comment by kanishkaa24** [comment]
Hey!
I would love to work on this.

**Comment by harsh-9in** [comment]
This issue was already solved :)
