### ISSUE TITLE
requirements.txt file

### ISSUE THREAD

**Issue by SubhradeepSS** [harsh-9in/Blogger#211]
**Describe the bug**
requirements.txt file is not having all the packages required to successfully run the project.

**Comment by SubhradeepSS** [comment]
@harsh-9in Can i solve this issue that i raised and make a PR?

**Comment by harsh-9in** [comment]
> **Describe the bug**
> requirements.txt file is not having all the packages required to successfully run the project.

Which packages are you taking about?? can you mantion some?

**Comment by SubhradeepSS** [comment]
> 
> 
> > **Describe the bug**
> > requirements.txt file is not having all the packages required to successfully run the project.
> 
> Which packages are you talking about?? can you mention some?

djangorestframework is not included

**Comment by harsh-9in** [comment]
okk go ahead :+1:

**Comment by SubhradeepSS** [comment]
@harsh-9in Can you please review my PR - #217 for this issue?

**Comment by SubhradeepSS** [comment]
@har

> 
> 
> okk go ahead 👍

Please increment my points (NWOC) for raising the issue and also review my PR - #217
