### ISSUE TITLE
project database-db.sqlite3

### ISSUE THREAD

**Issue by SubhradeepSS** [harsh-9in/Blogger#212]
**Describe the bug**
The project database `db.sqlite3` is not removed from the git reference, even though it is there in .gitignore file. This leads to a common database for every contributor which might create problems for a developer while using the project or testing his/her features.

**Comment by SubhradeepSS** [comment]
@harsh-9in Can I work on this issue and make a PR to solve it?

**Comment by harsh-9in** [comment]
Go ahead :+1:

**Comment by SubhradeepSS** [comment]
@harsh-9in Can you please review my PR - #216 for this issue?

**Comment by Akshit42-hue** [comment]
@harsh-9in Can I work on this issue . want to take it for DWOC

**Comment by harsh-9in** [comment]
> @harsh-9in Can I work on this issue . want to take it for DWOC

this issue is solved you can check out another issues.

**Comment by SubhradeepSS** [comment]
@harsh-9in Please increment my points for raising the issue and also review the corresponding PR - #216
