### ISSUE TITLE
Should I add NWOC in README under Open Source Program !!

### ISSUE THREAD

**Issue by Vishal-raj-1** [harsh-9in/Blogger#219]
This project is participating in NWOC. So README.md must show that!!

**Comment by Ak-panchal** [comment]
yes, can you assign me?

**Comment by Sloth-Panda** [comment]
can you give this to me?

**Comment by harsh-9in** [comment]
@Sloth-Panda go ahead

**Comment by Sloth-Panda** [comment]
@harsh-9in  can you please review this PR

**Comment by Vishal-raj-1** [comment]
@harsh-9in did you update my points for this issue ?
