### ISSUE TITLE
Update readme.md and contribution.md

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#222]
As we have updated the project setting that's why it requires to set configurations in .env file. To create .env file you can take reference from .env.example file. This thing is going to mention is contributing and readme file.

**Comment by Vrindagupta6828** [comment]
@harsh-9in I would like to work on it

**Comment by IshetaBansal** [comment]
I would like to work on this issue. But can you please elaborate on what we have to do regarding the .env file. Thank you.

**Comment by harsh-9in** [comment]
Issues are given on a first come first serve basis so @Vrindagupta6828 go ahead and make sure you successfully set up the project then make the file.
And @IshetaBansal you can check out other issues :)

**Comment by Vrindagupta6828** [comment]
@harsh-9in can you please elaborate a bit

**Comment by IshetaBansal** [comment]
> Issues are given on a first come first serve basis so @Vrindagupta6828 go ahead and make sure you successfully set up the project then make the file.
> And @IshetaBansal you can check out other issues :)

Hey! This is my first time. Can you suggest some issues for a beginner? Thank you.

**Comment by harsh-9in** [comment]
> @harsh-9in can you please elaborate a bit

Basically, I have made a  .env.example file in which I have written the configuration except for email and password of SMTP(user will use their data for that if they are working on authentication created part or registration part).
The thing is that while setting up the project they need to make the .env file in the same directory in which the .env.example is present before running any python related command.

This thing you have to show case in the readme and contributing.md file in a formal and easy way.

hope I have cleared your doubt If you still confused feel free to ask I will be happy to help.

**Comment by harsh-9in** [comment]
> > Issues are given on a first come first serve basis so @Vrindagupta6828 go ahead and make sure you successfully set up the project then make the file.
> > And @IshetaBansal you can check out other issues :)
> 
> Hey! This is my first time. Can you suggest some issues for a beginner? Thank you.

you can add an issue regarding adding a program section in the readme in which you are selected as a participant.
You can take reference of  hackincodes in the readme. And ask to assign that iise to your self :)

**Comment by harsh-9in** [comment]
> > > Issues are given on a first come first serve basis so @Vrindagupta6828 go ahead and make sure you successfully set up the project then make the file.
> > > And @IshetaBansal you can check out other issues :)
> > 
> > 
> > Hey! This is my first time. Can you suggest some issues for a beginner? Thank you.
> 
> you can add an issue regarding adding a program section in the readme in which you are selected as a participant.
> You can take reference of hackincodes in the readme. And ask to assign that issue to your self :)

Follow this thing if are are participating in DWOC

**Comment by IshetaBansal** [comment]
> > > > Issues are given on a first come first serve basis so @Vrindagupta6828 go ahead and make sure you successfully set up the project then make the file.
> > > > And @IshetaBansal you can check out other issues :)
> > > 
> > > 
> > > Hey! This is my first time. Can you suggest some issues for a beginner? Thank you.
> > 
> > 
> > you can add an issue regarding adding a program section in the readme in which you are selected as a participant.
> > You can take reference of hackincodes in the readme. And ask to assign that issue to your self :)
> 
> Follow this thing if are participating in DWOC

Thanks a lot! Getting to it right now :)

**Comment by tharunc** [comment]
Hello,
     I would like to work on the readme.md file issue . Can you please assign it to me.

**Comment by Vrindagupta6828** [comment]
I am working on it

**Comment by Vrindagupta6828** [comment]
@harsh-9in you have just written a secret key in .env.example so what i have to write in readme is that they have to make a env file in the same folder as .env.example??? Then what is the use of .env.example file?? And where i have to add it?

**Comment by harsh-9in** [comment]
Yeah, they have to make a .env file in that they have to copy the content of the .env.example file.

**Comment by Vrindagupta6828** [comment]
I just have to write this line the readme.md?

**Comment by harsh-9in** [comment]
> @harsh-9in you have just written a secret key in .env.example so what i have to write in readme is that they have to make a env file in the same folder as .env.example??? Then what is the use of .env.example file?? And where i have to add it?

That should be .env in the same directory, as .env.example is the file is there to take help to make .env file.

**Comment by harsh-9in** [comment]
> I just have to write this line the readme.md?

no, you have to elaborate this- you can take help of - https://github.com/harsh-9in/Blogger/issues/222#issuecomment-751384524

**Comment by Vrindagupta6828** [comment]
@harsh-9in You have explained the same thing there? What's different i am soo sorry but i am super confused

**Comment by harsh-9in** [comment]
Okk i no problem I am telling you in very simple way.

**Comment by Vrindagupta6828** [comment]
Create a new file in root folder of repository (WebApp) with name .env and add the following content in it:

EMAIL_HOST_USER = 'your-email@domain.com'
EMAIL_HOST_PASSWORD = 'your-password'

SENDER_EMAIL = ' <your-email@domain.com>'
ADMINS_EMAIL = ['email-address-of-admin@domain.com']

you want something like this?

**Comment by harsh-9in** [comment]
I have sent you instructions on gitter.

**Comment by Vrindagupta6828** [comment]
@harsh-9in gitter channel is not working i am suppose I am unable to open gitter

**Comment by harsh-9in** [comment]
In settings.py there is an email of the host, email password kind of thing which needs to be hidden from Github.


so there is .env file in which all those details are stored which are not shown in Github and it is also already included in .gitigonre file.
so that it does not show on github
but it is mandatory to run a project
so i have made a .env.example file
the content of .env.example will be copied and pasted into .env file so that settings.py file take all the configurations from .env file

**Comment by Vrindagupta6828** [comment]
@harsh-9in Ok thankyou soo much harsh i understood so in the readme i have to mention:
made a .env.example file
the content of .env.example will be copied and pasted into .env file so that settings.py file take all the configurations from .env file
is that ok?

**Comment by harsh-9in** [comment]
> @harsh-9in Ok thankyou soo much harsh i understood so in the readme i have to mention:
> made a .env.example file
> the content of .env.example will be copied and pasted into .env file so that settings.py file take all the configurations from .env file
> is that ok?

Yeeah exactly
