### ISSUE TITLE
Add DWOC in the Open Source Program Section in readme.

### ISSUE THREAD

**Issue by IshetaBansal** [harsh-9in/Blogger#223]
**Is your feature request related to a problem? Please describe.**
It's important to add this Project's participation in DWOC in its readme file as well. 

Please assign me to work on this if interested. Thank you :)

**Comment by harsh-9in** [comment]
Go ahead @IshetaBansal 👍

**Comment by Khimit** [comment]
Hello sir,
      I would like to work on this . Can you assign this task to me?

**Comment by harsh-9in** [comment]
> Hello sir,
> I would like to work on this . Can you assign this task to me?

Hey @Khimit , This task is already assigned to isheta so you can checkout other issues.

**Comment by chehak123** [comment]
hii 
i would like to work on this issue

**Comment by Sloth-Panda** [comment]
Hey, I would like to take this work

**Comment by harsh-9in** [comment]
This issue is already assigned : )
