### ISSUE TITLE
[Feature] View Profile for normal Users

### ISSUE THREAD

**Issue by Kajol-Kumari** [harsh-9in/Blogger#23]
Feature Request:
The users should be able to view the profile of the person who has created the blog by clicking on their name as being shown in the attached screenshot below:

Screenshot:
![imageedit_3_9993364021](https://user-images.githubusercontent.com/44888949/90281064-96328300-de89-11ea-8128-39a34f750814.gif)

**Comment by Akshi149** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Kajol-Kumari** [comment]
sure @Akshi149 You can work on this :)

**Comment by Akshi149** [comment]
@Kajol-Kumari on clicking should it redirect to the profile page or show the profile when we simply hover?
