### ISSUE TITLE
Want to beautify search blogs button

### ISSUE THREAD

**Issue by djm-1** [harsh-9in/Blogger#232]
**Is your feature request related to a problem? Please describe.**
the search blog button is not looking that great...it's tilted upwards

**Describe the solution you'd like**
A modern customized search button
**Describe alternatives you've considered**
i can improve the navbar by using bootstrap and css

**Comment by chehak123** [comment]
I want to work on this under DWOC

**Comment by ashima0699** [comment]
Please assign this to me @harsh-9in

**Comment by djm-1** [comment]
I created the issue and I can solve this.....assign it to me. 😀

**Comment by reenos-svg** [comment]
I can help you with this too

**Comment by harsh-9in** [comment]
Guys I am planning for changing the whole UI so there will be issues opening soon you can checkout those.
