### ISSUE TITLE
Beautify  the README with badges and  heading centered 

### ISSUE THREAD

**Issue by akrish4** [harsh-9in/Blogger#233]
### **Is your feature request related to a problem? Please describe.**
I would like to beautify the readme file with badges and making the header center and improving little which gives it a stunning look since readme file is the thing people see first and notice 

### **Describe the solution you'd like**
I would like to beautify the readme file with badges and making the header center and improving little

### **Describe alternatives you've considered**
I am already experienced in making the readme file look nice 

### **Additional context**

![readme1](https://user-images.githubusercontent.com/61831021/103415818-cb760e00-4ba9-11eb-87fc-124ee0fc5ad6.PNG)

@harsh-9in 
Kindly assign me this issue

**Comment by harsh-9in** [comment]
go ahead :+1:

**Comment by Rishikeshrajrxl** [comment]
hey @harsh-9in please assign me this issue, I have already made it and ready to push.

**Comment by akrish4** [comment]
> hey @harsh-9in please assign me this issue, I have already made it and ready to push.

@Rishikeshrajrxl 
First go read the rules of DWOC ,
- the issue is assigned is to the person who create the issue 
you can't push , don't violate the rules @Rishikeshrajrxl

**Comment by Rishikeshrajrxl** [comment]
> > hey @harsh-9in please assign me this issue, I have already made it and ready to push.
> 
> @Rishikeshrajrxl
> First go read the rules of DWOC ,
> 
> * the issue is assigned to the person who opens the issue
>   you can't push, don't violate the rules @Rishikeshrajrxl

@akrish4  I am not pushing any code without being assigned, so please stay calm.

**Comment by harsh-9in** [comment]
Calm down buddies as this was assigned to @akrish4 so his pr will be considered, @Rishikeshrajrxl plz try another issue which is not assigned.
