### ISSUE TITLE
Broken Images on CONTRIBUTING.md

### ISSUE THREAD

**Issue by jveer634** [harsh-9in/Blogger#238]
**Images used on Contributing are broken**

**To Reproduce**
1. Go to 'Contributing.md'
1. See images missing

**Expected behavior**
Display Images

**Screenshots**
![image](https://user-images.githubusercontent.com/47923507/103546812-96c7c680-4ec9-11eb-8eb4-0c80a675ee5c.png)

**Comment by harsh-9in** [comment]
you can remove those broken images
