### ISSUE TITLE
[Feature] Like the post Feature

### ISSUE THREAD

**Issue by Kajol-Kumari** [harsh-9in/Blogger#24]
Deliverables:

- [ ] Backend API for keeping the record of likes of the post.

- [ ] Frontend UI to like the post on the Blog card.

**Comment by ritiksoni00** [comment]
any Resources {i search it but....}??  i don't know anything About it but want to know...

**Comment by ymaheshwari1** [comment]
I am interested in working on this issue.

**Comment by AkM-2018** [comment]
https://stackoverflow.com/questions/15407985/django-like-button
https://www.youtube.com/watch?v=VoWw1Y5qqt8
https://www.youtube.com/watch?v=PXqRPqDjDgc

I would like to work on this if you're not interested @ritiksoni00. Pls comment if you're not.

**Comment by ritiksoni00** [comment]
@AkM-2018 I'm interested I want to work as I'm a beginner so if it is possible that we can work together?? @Kajol-Kumari  Please suggest us What should we do???

**Comment by ritiksoni00** [comment]
> https://stackoverflow.com/questions/15407985/django-like-button
> https://www.youtube.com/watch?v=VoWw1Y5qqt8
> https://www.youtube.com/watch?v=PXqRPqDjDgc
> 
> I would like to work on this if you're not interested @ritiksoni00. Pls, comment if you're not.

Thank you for this @AkM-2018 
will I able to solve this issue via these resources ???

**Comment by AkM-2018** [comment]
You need to know how to work with django, some basic knowledge. Also some basic html. 
You can then follow the vid. It will be straight forward then.

**Comment by Kajol-Kumari** [comment]
Hey @ritiksoni00 as you already have two issues assigned to you, I am assigning it to @AkM-2018.

**Comment by ritiksoni00** [comment]
hahaha ! It's not like I want to assigned me for all the issues i just want to try new challenges

**Comment by ritiksoni00** [comment]
> You need to know how to work with django, some basic knowledge. Also some basic html.
> You can then follow the vid. It will be straight forward then.
> I don't know how we'll work together. Take the issue. If you can't solve it within some days, I'll ask @Kajol-Kumari reassign it to me.
> Is it okay, @Kajol-Kumari ?

Thankyou @AkM-2018

**Comment by AkM-2018** [comment]
Just to notify...

Since the individual blog posts pull request is in process, I've put the like button directly on the home page(for now). 

![like_button](https://user-images.githubusercontent.com/50191787/90473949-cefc8180-e141-11ea-97bb-d27d56127aee.JPG)

The user can like a post only when logged in. Else he is redirected to the login page.

One problem I'm facing is, whenever someone likes the post he is sent back to the top of the home page due to HttpRedirectResponse(reverse('blog-home')).

**Comment by AkM-2018** [comment]
@Kajol-Kumari, that was not the problem I was facing. Anyways, I've put a pull request. Lemme know the changes if any

**Comment by kritikaparmar-programmer** [comment]
Hey @Kajol-Kumari can I work on this issue??

**Comment by Kajol-Kumari** [comment]
Hey @AkM-2018 can you please provide me your work status for this issue as you were supposed to open up a new PR for this issue. @kritikaparmar-programmer Let's wait for 3 days, if @AkM-2018 won't response i'll assign it to  you.

**Comment by kritikaparmar-programmer** [comment]
@Kajol-Kumari  Okay 👍

**Comment by AkM-2018** [comment]
There's some bug in my code which I'm not able to figure out. I've spent a lot of time on this issue. Pls, reassign it to someone else.

**Comment by Kajol-Kumari** [comment]
@kritikaparmar-programmer would you like to go ahead with this issue?

**Comment by kritikaparmar-programmer** [comment]
Yess @Kajol-Kumari

**Comment by harsh-9in** [comment]
@kritikaparmar-programmer are you still working on this issue.

**Comment by kritikaparmar-programmer** [comment]
Yes I'm working on this issue though facing some issues I'll let you know @harsh-9in

**Comment by harsh-9in** [comment]
okk @kritikaparmar-programmer

**Comment by kritikaparmar-programmer** [comment]
hey @harsh-9in and @Kajol-Kumari please assign this issue to someone else. I don't know why I'm facing issues. Better not to waste time.

**Comment by nooras** [comment]
Can I try this ? @Kajol-Kumari

**Comment by ExpressHermes** [comment]
@Kajol-Kumari I think we can use Ajax to implement like button. Furthermore, using jQuery will immensely decrease the difficulty. I would like to work on this.

**Comment by TrushaT** [comment]
Can I be assigned this issue? @harsh-9in .

**Comment by harsh-9in** [comment]
Go ahead :+1:
