### ISSUE TITLE
[Feature] Edit Profile

### ISSUE THREAD

**Issue by Kajol-Kumari** [harsh-9in/Blogger#25]
Account Holder should be able to edit his/her profile details.

Deliverables:

- [ ] Backend API for editing profile details.

- [ ] Frontend changes on the UI for the Feature.

**Comment by Akshi149** [comment]
Are we supposed to make a separate template for editing profile?

**Comment by ymaheshwari1** [comment]
I am interested in working on this issue.

**Comment by Kajol-Kumari** [comment]
Yes @Akshi149, we will need to have a separate template for allowing the users ro edit their details. @ymaheshwari1 I am assigning this to you as @Akshi149 already have 2 issues assigned to her.

**Comment by ymaheshwari1** [comment]
ok @Kajol-Kumari
