### ISSUE TITLE
[Enhancement] Redirect on Home page after logging out

### ISSUE THREAD

**Issue by Kajol-Kumari** [harsh-9in/Blogger#26]
Currently we are using a separate template for logOut page [this one](https://github.com/harsh-9in/Blogger/blob/master/mysite/users/templates/user/logout.html) which seems quiet unneccesary.

Deliverables:

- [ ] Remove the [logOut template](https://github.com/harsh-9in/Blogger/blob/master/mysite/users/templates/user/logout.html)

- [ ] Redirect to home page after user logs out of the site.

**Comment by diyajaiswal11** [comment]
@Kajol-Kumari  I'm interested in solving this issue. Please assign this to me.

**Comment by Himanshu44626748** [comment]
I would like to work on this. Please assign me.

**Comment by Kajol-Kumari** [comment]
Hey @Himanshu44626748 please look for the other opened issues or wait for the other issues to be opened as we need to follow FCGS :)
