### ISSUE TITLE
Design a wireframe for dashboard page

### ISSUE THREAD

**Issue by Swarnimashukla** [harsh-9in/Blogger#31]
Task

You are supposed to create a dashboard page for website that user can access after logging in and check for stats.

**Features**

We can add following features ondashboard but not restricted to these you can use your own creativity .

1. Number of blogs user has written 
2. Top featured blog by user 
3. Total stars of that particular user( as blogs have reactions and according to quality stars can be given)
4. Comments and views on blogs 
5. Followers 
6. User engagement with content via graph(time spent on read blogs) 

Again these are suggestions we would love to see your creativity

**Implementation**

Tools used : Figma , Balsamiq (make sure you create professional wireframes )
Create designs and share screenshots in comment section
Once finalized create PR

**Procedure**

Claim this issue: Comment below that you want to work on this issue
Write relevant commit message while making a PR
Create a PR with self closing tags

**Comment by swapniltripathi123** [comment]
I want to work on this issue

**Comment by Swarnimashukla** [comment]
Hey @swapniltripathi123  currently you are assigned to two issues so you need finish those works first then I will assign this to you

**Comment by nooras** [comment]
Hello maam Can i do this ? I am interested in UI too. Also I want to know can I use colors or only you need black and white wireframes ? @swapniltripathi123

**Comment by Swarnimashukla** [comment]
@nooras  yes you can work on this issue and  we haven't discussed color palette of complete website yet , so maybe initially you can create basic wireframe or if you want you can use color as well no issues .

**Comment by nooras** [comment]
# Dasboard of users
 - Checkout @Swarnimashukla ... If anything needed let me know. I just tried 😅
![Dashboard](https://user-images.githubusercontent.com/30138146/90415381-a1c2bb80-e0ce-11ea-8e42-b00ab9189967.png)

**Comment by Swarnimashukla** [comment]
@nooras I really like this 😍  , there can be few changes like header could have actual icons , footer is missing , but I would say for a wireframe this looks nice to me , we can be more specific during ui designing after wireframe part is done .

Looking forward for your work in upcoming UI issues  :🙌✨✨

You can go for pr 👍
