### ISSUE TITLE
License not added

### ISSUE THREAD

**Issue by jivthesh** [harsh-9in/Blogger#33]

**Comment by jivthesh** [comment]
@harsh-9in I would like to work on this issue ?

**Comment by harsh-9in** [comment]
Yeah @jivthesh, You can Work on this issue.

**Comment by jivthesh** [comment]
#33 Issue solved

**Comment by AbhipsaGuru1012** [comment]
Hi, is this issue still open?

**Comment by jivthesh** [comment]
@AbhipsaGuru1012 no

**Comment by yashgautam9274** [comment]
I want to work on this issue

**Comment by harsh-9in** [comment]
This issue is already solved :)
