### ISSUE TITLE
[Feature] Add a Search Bar

### ISSUE THREAD

**Issue by ManishShah120** [harsh-9in/Blogger#39]
Currently, the *Home Page* of this App doesn't contain any searching option throughout all the posted Blog Posts, So what if any user wants to read blog posts according to his or her interests only? So,
I am thinking of adding a **`Search Card`** feature where any user can search through all the blog posts, and that would return only those blogs which matches to the user's **`search query`**.

**Comment by ManishShah120** [comment]
I am interested in working on this issue, Kindly assign me with the required tags.

**Comment by Kajol-Kumari** [comment]
Hey @ManishShah120 please keep it on the header for now. We will shift that after the home page UI design is prepared.

**Comment by ManishShah120** [comment]
Okay @Kajol-Kumari
