### ISSUE TITLE
Should make a new CONTRIBUTING.MD file

### ISSUE THREAD

**Issue by ritiksoni00** [harsh-9in/Blogger#48]
**Is your feature request related to a problem? Please describe.**
README,md  file has Contribution Guidelines which is not good I thing! 

**Describe the solution you'd like**
ill create a separate File for this

**Comment by sayashchaudhary** [comment]
i can do it

**Comment by ritiksoni00** [comment]
@sayashchaudhary  I'm also a Participates !! sorry

**Comment by Kajol-Kumari** [comment]
@ritiksoni00 can you please elaborate a little bit here what extra things you goona add/modify in there? (May be you can just paste here the things you are planning to add in the contribution.md file)

**Comment by ritiksoni00** [comment]
like contribution guidelines ... should be in this file!!

**Comment by Kajol-Kumari** [comment]
@ritiksoni00 please go ahead.

**Comment by ritiksoni00** [comment]
You should warn me! @Kajol-Kumari   ABOUT THIS #107
