### ISSUE TITLE
Addition of speech to text feature like listens to you and converts it to text similarly.

### ISSUE THREAD

**Issue by manikasharma09** [harsh-9in/Blogger#51]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ymaheshwari1** [comment]
@manikasharma09 You need to provide the description of your issue and other details by updating the content of the issues template. You can refer #45

**Comment by harsh-9in** [comment]
@manikasharma09 plz clarify your issue.
