### ISSUE TITLE
Update the "Setting Up Project" section in the README.md file

### ISSUE THREAD

**Issue by ymaheshwari1** [harsh-9in/Blogger#55]
**Describe the bug**
While setting up the project we need to include a step to create a virtual environment and then the user has to execute the requirements.txt file

**Additional context**
This will maintain a different environment for the project and the project dependencies will not affect other projects.

**Comment by ymaheshwari1** [comment]
I am interested in working on this.

**Comment by harsh-9in** [comment]
Go ahead @ymaheshwari1
