### ISSUE TITLE
Add Issue and pull request templates

### ISSUE THREAD

**Issue by Kajol-Kumari** [harsh-9in/Blogger#6]
**Deliverables**

- [ ] A template for issue creation.

- [ ] A template for making pull requests.

Reference Resources:https://medium.com/@ramsunvtech/github-templates-f9223da738a4
https://medium.com/better-programming/github-templates-the-smarter-way-to-formalize-pull-requests-among-development-teams-89f8d6a204f

**Comment by ritiksoni00** [comment]
@Kajol-Kumari  What i understand by A template?? what should i have to do

**Comment by ritiksoni00** [comment]
i think in readme file  write a section about issues and Making Pr????

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari What i understand by A template?? what should i have to do
Hey @ritiksoni00  by a template, i mean the prototype that will appear when user tries to create an issue or a Pull request. 
For getting clear idea regarding this, please see the reference resources i added in the description.

**Comment by Sapna2001** [comment]
@Kajol-Kumari can I work on this?

**Comment by ritiksoni00** [comment]
@Sapna2001  I'm working on templates one you can take the issues template! Ohkay??

**Comment by Kajol-Kumari** [comment]
Hey @Sapna2001 as @ritiksoni00 has already started working on it so you can look for the other PRs we will be opening soon.

**Comment by ritiksoni00** [comment]
i thing there you should assign me???  if its important???
