### ISSUE TITLE
Adding the informative messages for the user

### ISSUE THREAD

**Issue by ymaheshwari1** [harsh-9in/Blogger#61]
**Describe the bug**
When a user is logging out or logging in, there is no message displayed to the user whether the action is successfully performed or not.

**To Reproduce**
1. Log In to your account
2. You will be redirected to the Home Page but no message is displayed to the User about the activity.
3. Log Out of your account.
4. You will be redirected to the Home Page but no message is displayed to the User about the activity.

**Expected behavior**
*A completion message needs to be displayed to the user. Like, You are logged In successfully or You are logged out successfully.*

**Comment by ymaheshwari1** [comment]
I am interested in working on this.

**Comment by harsh-9in** [comment]
@ymaheshwari1  whare do you want to show the message?

**Comment by ymaheshwari1** [comment]
@harsh-9in As the User is redirected to the Home screen, so we can show the message on the Home Screen

**Comment by Kajol-Kumari** [comment]
@ymaheshwari1 how about showing this in the form of notification?

**Comment by ymaheshwari1** [comment]
@Kajol-Kumari Yes we can do that as well, we can use snackbar
https://www.w3schools.com/howto/howto_js_snackbar.asp

**Comment by Kajol-Kumari** [comment]
@ymaheshwari1 please go ahead with slackbar/notification/toast message :)
