### ISSUE TITLE
Having error while running the project

### ISSUE THREAD

**Issue by ymaheshwari1** [harsh-9in/Blogger#70]
**Describe the bug**
When starting the server it throws an error that "cannot import name post"

**To Reproduce**
1. Go to the project
2. Run command **python manage.py runserver**
3. See error

**Expected behavior**
The project should run without throwing any errors

**Comment by ymaheshwari1** [comment]
I am interested in working on this.

**Comment by Ahana001** [comment]
I am also interested.

**Comment by Akshi149** [comment]
@ymaheshwari1 I guess this error is because of my PR because when I created PR name of the model was "post", not "Post".o I have resolved it and will do the commit in a min.

**Comment by ymaheshwari1** [comment]
The error is resolved and we can close this issue. @Kajol-Kumari
