### ISSUE TITLE
UI design for Home page of Blogger 

### ISSUE THREAD

**Issue by Swarnimashukla** [harsh-9in/Blogger#77]
**Is your feature request related to a problem? Please describe.**
UI design for Home Page of Blogger

**Describe the solution you'd like**

***UI design is exact replica of what your website will look like***

This task is connected with issue #11 check for wireframes designed for this page and create a UI design for the same using color palette and font styling (for color and font check issue #45 )

**Additional context**

As we have more than one wireframe for a page so you can either choose a single wireframe and convert it into UI or use features from different wireframes designed by participants and come up with great solution .

Considering UI we expect a high fidelity design , use proper heading title without lorem ipsum .

**Comment by ymaheshwari1** [comment]
I am interested

**Comment by Akshi149** [comment]
I am interested

**Comment by raksha009** [comment]
I am interested

**Comment by Swarnimashukla** [comment]
@ymaheshwari1  you are already assigned 2 issues and @raksha009  as @Akshi149 commented earlier so I am currently assigning it to her .

**Comment by Akshi149** [comment]
![Group 3homepage](https://user-images.githubusercontent.com/69034239/91215943-ce13b300-e732-11ea-9a2d-73960fa0cc51.png)
@Swarnimashukla your views on this design. Any changes to be made?

**Comment by BellatrixLestrangee** [comment]
Greetings @Swarnimashukla . Can I make a attempt towards this issue?

**Comment by Swarnimashukla** [comment]
@Akshi149  this looks good to me , go for a pr , name your screenshot - Homepage_ui_yourname
