### ISSUE TITLE
UI design for dashboard Page of Blogger

### ISSUE THREAD

**Issue by Swarnimashukla** [harsh-9in/Blogger#78]
**Is your feature request related to a problem? Please describe.**
UI design for dashboard Page of Blogger

**Describe the solution you'd like**

***UI design is exact replica of what your website will look like***

This task is connected with issue #31  check for wireframes designed for this page and create a UI design for the same using color palette and font styling (for color and font check issue #45 )

**Additional context**

As we have more than one wireframe for a page so you can either choose a single wireframe and convert it into UI or use features from different wireframes designed by participants and come up with great solution .

Considering UI we expect a high fidelity design , use proper heading title without lorem ipsum .

**Comment by nooras** [comment]
I am interested @Swarnimashukla

**Comment by Swarnimashukla** [comment]
@nooras  what's the update with design ?

**Comment by nooras** [comment]
> @nooras what's the update with design ?

Work is in progress... Will share you soon...

**Comment by nooras** [comment]
### Dasboard UI done... Checkout @Swarnimashukla and let me know if any changes is required...

![FinalDashboard](https://user-images.githubusercontent.com/30138146/91418906-66638200-e870-11ea-955c-00ec7dd30a35.png)

**Comment by Swarnimashukla** [comment]
@nooras its good , but slight different from other pages anyways go for pr , we will change things in coding phase if required.

**Comment by nooras** [comment]
> @nooras its good , but slight different from other pages anyways go for pr , we will change things in coding phase if required.

What else I can do ? Ma'am ?

**Comment by Swarnimashukla** [comment]
@nooras  sure , Few things I would suggest :  

1. Use  background color in header as well like footer
2. Enhance font size in footer section (about , home etc) as they are not clear and difficult to read now, keep them simple not italic , its important to use familiar fonts , styles to make user friendly designs 
3. Remove border from header section's terms like home , about , notification it might look aesthetically pleasing but we need similar designs for every page also I am comparing it for flexibility and ease while coding 
4. You can use small icons as well in front of home , notification etc in header 
5. Give some background color to whole page so that every sections pops up little bit .

**Comment by nooras** [comment]
> @nooras sure , Few things I would suggest :
> 
> 1. Use  background color in header as well like footer
> 2. Enhance font size in footer section (about , home etc) as they are not clear and difficult to read now, keep them simple not italic , its important to use familiar fonts , styles to make user friendly designs
> 3. Remove border from header section's terms like home , about , notification it might look aesthetically pleasing but we need similar designs for every page also I am comparing it for flexibility and ease while coding
> 4. You can use small icons as well in front of home , notification etc in header
> 5. Give some background color to whole page so that every sections pops up little bit .

![Group 4 (3)](https://user-images.githubusercontent.com/30138146/91641102-ec81f300-ea3f-11ea-984f-5fa2ade7aeb4.png)
Update done @Swarnimashukla

**Comment by Swarnimashukla** [comment]
perfect @nooras  go for pr

**Comment by nooras** [comment]
In static file> dashboard ui_nooras i have to put it ?
