### ISSUE TITLE
UI design for community page of Blogger

### ISSUE THREAD

**Issue by Swarnimashukla** [harsh-9in/Blogger#79]
**Is your feature request related to a problem? Please describe.**
UI design for community Page of Blogger

**Describe the solution you'd like**

***UI design is exact replica of what your website will look like***

This task is connected with issue #18  check for wireframes designed for this page and create a UI design for the same using color palette and font styling (for color and font check issue #45 )

**Additional context**

As we have more than one wireframe for a page so you can either choose a single wireframe and convert it into UI or use features from different wireframes designed by participants and come up with great solution .

Considering UI we expect a high fidelity design , use proper heading title without lorem ipsum .

**Comment by ymaheshwari1** [comment]
I am interested

**Comment by AdityaAshvin** [comment]
Can i do this task @Swarnimashukla ?

**Comment by Swarnimashukla** [comment]
@ymaheshwari1 , you are already working on 2 issues so I am assigning it to @AdityaAshvin

**Comment by raksha009** [comment]
I  am interested. Plz asign this task to me too.

**Comment by Swarnimashukla** [comment]
@raksha009  this task is assigned on FCFS basis we don't have this issue open for all

**Comment by AdityaAshvin** [comment]
![Design 2](https://user-images.githubusercontent.com/53205379/90986933-6cbdd980-e5a4-11ea-8fa8-313275e881d5.JPG)

@Swarnimashukla your views about this design. any changes to be made?

**Comment by Swarnimashukla** [comment]
@AdityaAshvin it looks good , here are few changes I would suggest : 

1. In header keep profile only , remove logout once user clicks on profile he can get a dropdown for it , it need not be a individual icon on header 

2. Put search symbol inside search area before text and maybe reply "type a keyword" with "search here" or maybe "search communities" only because search is more common than keyword

3. Keep text color in header and footer black/white only , pink seems little dull with grey background 

4. In newsletter section write "enter your email address"  or  "enter your email id"  in place of " your mail id"

This will help page look more clear and easy to use
