### ISSUE TITLE
Creating Bolg/Post

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#8]
We can create blogs/posts from the command line/terminal right now.
Add functionality to create blogs through the web interface.

**Comment by nooras** [comment]
You mean to say we have to create post app in django? right and have to add create blog by clicking create? @harsh-9in

**Comment by nooras** [comment]
And what what inputs will be there ? like Title, description, image And ??? @harsh-9in

**Comment by harsh-9in** [comment]
> You mean to say we have to create post app in django? right and have to add create blog by clicking create? @harsh-9in

I have already created app for that 
you can checkout `blog` app for that 

The thing you have to do is to make a form which takes data for our blog and show it on home page.

**Comment by harsh-9in** [comment]
> And what what inputs will be there ? like Title, description, image And ??? @harsh-9in

You have to take two inputs for now that is **Title** and **description**.
we will make a support for image in future.

**Comment by nooras** [comment]
Okay so I will do this please assign me okay @harsh-9in ?

**Comment by harsh-9in** [comment]
yeah sure go ahead :)  @nooras

**Comment by nooras** [comment]
I have 1 request please also tag the task is easy medium or hard . Coz I think due to this we will get points :) Thanks

**Comment by kritikaparmar-programmer** [comment]
I want to work in this issue.

**Comment by nooras** [comment]
Hey @kritikaparmar-programmer task is already done...
