### ISSUE TITLE
UI design for community page(expanded) of Blogger 

### ISSUE THREAD

**Issue by Swarnimashukla** [harsh-9in/Blogger#80]
**Is your feature request related to a problem? Please describe.**
UI design for community Page (particular page)of Blogger

**Describe the solution you'd like**

***UI design is exact replica of what your website will look like***

This task is connected with issue #49 check for wireframes designed for this page and create a UI design for the same using color palette and font styling (for color and font check issue #45 )

**Additional context**

As we have more than one wireframe for a page so you can either choose a single wireframe and convert it into UI or use features from different wireframes designed by participants and come up with great solution .

Considering UI we expect a high fidelity design , use proper heading title without lorem ipsum .

**Comment by ymaheshwari1** [comment]
I am interested

**Comment by ymaheshwari1** [comment]
@Swarnimashukla Please have a look at the following UI
![Community - Home UI](https://user-images.githubusercontent.com/41404838/91251716-a431af00-e779-11ea-90df-c687f4c0077d.png)

**Comment by Swarnimashukla** [comment]
It looks good , go for pr @ymaheshwari1
