### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by AkM-2018** [harsh-9in/Blogger#82]
**Describe the bug**
Firstly, on running it shows an import error(discussed in #70). On making the changes and running the project, the layout of the home page is disturbed. Also, there are two headings for each blog.

**To Reproduce**
1. Fetch the master branch from harsh-9in/Blogger and merge with your local master.
2. Checkout to a branch
3. Run python manage.py makemigrations, python manage.py migrate, python manage.py runserver

**Screenshots**

![homepage_](https://user-images.githubusercontent.com/50191787/90856718-37489e80-e3a0-11ea-9917-d071f4695296.jpg)

**Why this error**
1. Typo in models.py between 'post' and 'Post'
2. One div opening tag missing in templates/blog/home.html
3. Extra set of 'h2' and 'p' tags in templates/blog/home.html

**Comment by ymaheshwari1** [comment]
@AkM-2018 The issue have a PR once it will be merged then the project will run smoothly.
