### ISSUE TITLE
Home Page UI

### ISSUE THREAD

**Issue by harsh-9in** [harsh-9in/Blogger#9]
Make ui of the home page more attractive.
You can use HTML,CSS,Bootstrap.

**Comment by ymaheshwari1** [comment]
Hi,
What kind of UI, we are expecting?

**Comment by ymaheshwari1** [comment]
I am willing to work on the UI.

**Comment by itsarjun12** [comment]
I can work on this.

**Comment by itsarjun12** [comment]
tell me about what kind of page you need?

**Comment by Swarnimashukla** [comment]
Hey everyone , we are looking for a home page which includes blogs written by users , categories section from where reader can choose what kind of blog they are looking for , page where they could write their own blog . These all features are supposed to be on home page . I will be opening new issues for different page design , firstly we need to design wireframes for website

**Comment by raksha009** [comment]
Hi, I would like to work on this issue. Plz assign it to me.

**Comment by harsh-9in** [comment]
We are creating different ui for different UI parts so I am closing this issue.
@raksha009  you can check out those issues :)
