### ISSUE TITLE
[Enhancement] Improve Edit profile MOdal

### ISSUE THREAD

**Issue by Kajol-Kumari** [harsh-9in/Blogger#91]
Current UI:
![Screenshot from 2020-08-23 13-42-58](https://user-images.githubusercontent.com/44888949/90974354-102cd100-e548-11ea-80b0-6ac0323ac973.png)

This UI should me made better and more user friendly.

**Comment by kritikaparmar-programmer** [comment]
Hey @Kajol-Kumari , I've one doubt. Sorry for asking late But you mentioned in the issue to improve the edit profile model but in the screen shot the profile picture thing is showing.. Can you please elaborate a bit on the issue, It would be great ..

**Comment by Kajol-Kumari** [comment]
Hey @kritikaparmar-programmer in the image about you see the popup that has appeared for file upload. There you see the `file upload` option is not properly aligned. Also there is no message showing up the purpose of that dialogue box  ( which in this case should be `please select a new image` )etc.These things need to be improved and organised.

**Comment by kritikaparmar-programmer** [comment]
Ok 👍
