### ISSUE TITLE
[Bug] View profile for blog creator showing error 

### ISSUE THREAD

**Issue by Kajol-Kumari** [harsh-9in/Blogger#93]
**Bug Description**
View profile for blog creator throwing error .
steps for bug recreation:
1. Log In
1. Create a blog
2. Remain logged in and click on your name shown above the blog.

GIF:
![bug_view_creator_profile](https://user-images.githubusercontent.com/44888949/90974464-1ec7b800-e549-11ea-99b2-3752ea74ea3a.gif)

**Comment by Kajol-Kumari** [comment]
> @kajol but I have created the PRs for the issues.

Yes @ymaheshwari1 you need to get atleast one of your PR merged for taking up a new issue. sorry but we need to follow this so that everyone gets a chance to learn :)

**Comment by shraddhavp** [comment]
@Kajol-Kumari  mam made the PR please check it
