### ISSUE TITLE
Forgot_Password throwing Error

### ISSUE THREAD

**Issue by Ahana001** [harsh-9in/Blogger#96]
**Describe the bug**
It throws out the error when we enter the email.

**Screenshots**
![Forget_Password_error](https://user-images.githubusercontent.com/50478681/90982548-5fddbd80-e585-11ea-9c7c-9bb55d55d1f7.gif)

**Comment by Akshi149** [comment]
@Kajol-Kumari @Ahana001 this issue is because email id and password need to be of the (sender)admin in the settings.py

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari @Ahana001 this issue is because email id and password need to be of the (sender)admin in the settings.py

Hey @Akshi149 If this is the case then we should remove this hardcoding thing and instead store all the registered emails in the db and after user enters the emailID for resetting the password, it should be checked from database if that emailID exists or not and then proceed accordingly.

**Comment by Akshi149** [comment]
@Kajol-Kumari this is already being followed. The thing is either the mail is sent on console or on Gmail and in order to send it on Gmail, sender's email id is required (which will be of app owner) from whom user will receive the mail for resetting the password.

\cc: @Ahana001

**Comment by Akshi149** [comment]
Just sender's email id is to be written there

**Comment by Kajol-Kumari** [comment]
@Akshi149 I see... But ideally it's should the person's emailId who want to reset the password not the app owner's email. Maybe we should work on implementing this.

\cc: @Ahana001

**Comment by Akshi149** [comment]
@Kajol-Kumari U mean email should be send by and receive on same email id?

**Comment by Kajol-Kumari** [comment]
@Akshi149 I mean that the person who wants to reset his/her password should enter his/her emailID in the forget password page and he/she will receive the main on that particular ID. Probably i am missing something here. If it's so please let me know.

**Comment by Akshi149** [comment]
@Kajol-Kumari it works like this only 
I m saying that in settings.py file we need to change the EMAIL_HOST_USER and EMAIL_HOST_PASSWORD with the app owner's details so that the person who wants to change the password can get the link on his/her entered email-id from the owner

**Comment by Akshi149** [comment]
![Uploading IMG_20200824_202041.jpg…]()
This place has to be filled with owner's details

**Comment by Ahana001** [comment]
> 
> 
> @Akshi149 I see... But ideally it should be the person's emailId who want to reset the password not the app owner's email. Maybe we should work on implementing this.
> 
> \cc: @Ahana001

yes @Kajol-Kumari

**Comment by Akshi149** [comment]
![IMG_20200824_202041](https://user-images.githubusercontent.com/69034239/91065524-36d52f80-e64e-11ea-9ed1-511fc174e470.jpg)

**Comment by Akshi149** [comment]
In settings.py file

**Comment by Akshi149** [comment]
@Ahana001 Rest works as it suppose to be

**Comment by Akshi149** [comment]
@Ahana001 if you are not able to do it, please assign this to me @Kajol-Kumari

**Comment by Ahana001** [comment]
@Kajol-Kumari assign this issue to @Akshi149

**Comment by kritikaparmar-programmer** [comment]
Hey @Kajol-Kumari  I want to work on this is issue.. Please assign me..

**Comment by Kajol-Kumari** [comment]
sure @kritikaparmar-programmer ! Please go ahead with issue :)
